apiVersion: kion.upbound.io/v1alpha1
kind: IAMPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: kion/v1alpha1/iampolicy
  labels:
    testing.upbound.io/example-name: p1
  name: p1
spec:
  forProvider:
    name: sample-resource
    ownerUserGroups:
    - id: 1
    ownerUsers:
    - id: 1
    policy: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Action": "*",
                  "Resource": "*"
              }
          ]
      }
