apiVersion: kion.upbound.io/v1alpha1
kind: ServiceControlPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: kion/v1alpha1/servicecontrolpolicy
  labels:
    testing.upbound.io/example-name: protect_critical_services
  name: protect-critical-services
spec:
  forProvider:
    description: Prevents modification of critical AWS services and configurations
    name: Protect Critical Services
    ownerUserGroups:
    - id: 20
    ownerUsers:
    - id: 10
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Deny",
            "Action": [
              "config:DeleteConfigurationRecorder",
              "config:StopConfigurationRecorder",
              "cloudtrail:StopLogging",
              "cloudtrail:DeleteTrail",
              "guardduty:DeleteDetector",
              "guardduty:DisassociateFromMasterAccount"
            ],
            "Resource": "*"
          }
        ]
      }
