apiVersion: kion.upbound.io/v1alpha1
kind: Source
metadata:
  annotations:
    meta.upbound.io/example-id: kion/v1alpha1/source
  labels:
    testing.upbound.io/example-name: fs1
  name: fs1
spec:
  forProvider:
    amount: 10000
    description: Sample funding source created via terraform
    endDatecode: 2023-12
    name: Test Funding
    ouId: 1
    ownerUserGroups:
    - id: 3
    ownerUsers:
    - id: 1
    permissionSchemeId: 4
    startDatecode: 2023-01
