// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AzureAccountInitParameters struct {

	// (String) Account alias is an optional short unique name that helps identify the account within Kion.
	// Account alias is an optional short unique name that helps identify the account within Kion.
	AccountAlias *string `json:"accountAlias,omitempty" tf:"account_alias,omitempty"`

	// (Number) An ID representing the account type within Kion.
	// An ID representing the account type within Kion.
	AccountTypeID *float64 `json:"accountTypeId,omitempty" tf:"account_type_id,omitempty"`

	// (Block Set, Max: 1) Parameters used when creating a new Azure CSP subscription. (see below for nested schema)
	// Parameters used when creating a new Azure CSP subscription.
	Csp []CspInitParameters `json:"csp,omitempty" tf:"csp,omitempty"`

	// (Block Set, Max: 1) Parameters used when creating a new Azure EA subscription. (see below for nested schema)
	// Parameters used when creating a new Azure EA subscription.
	Ea []EaInitParameters `json:"ea,omitempty" tf:"ea,omitempty"`

	// (Map of String) A map of labels to assign to the account. The labels must already exist in Kion.
	// A map of labels to assign to the account. The labels must already exist in Kion.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Block Set, Max: 1) Parameters used when creating a new Azure MCA subscription. (see below for nested schema)
	// Parameters used when creating a new Azure MCA subscription.
	Mca []McaInitParameters `json:"mca,omitempty" tf:"mca,omitempty"`

	// (Block Set, Max: 1) Parameters used when moving an account between Kion projects.  These settings are ignored unless moving an account. (see below for nested schema)
	// Parameters used when moving an account between Kion projects.  These settings are ignored unless moving an account.
	MoveProjectSettings []AzureAccountMoveProjectSettingsInitParameters `json:"moveProjectSettings,omitempty" tf:"move_project_settings,omitempty"`

	// (String) The name of the Azure account within Kion.
	// The name of the Azure account within Kion.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The parent management group ID when creating an Azure subscription. If provided, the subscription will be created under the provided management group.  If not provided, the subscription will be created at the root level
	// The parent management group ID when creating an Azure subscription. If provided, the subscription will be created under the provided management group.  If not provided, the subscription will be created at the root level
	ParentManagementGroupID *string `json:"parentManagementGroupId,omitempty" tf:"parent_management_group_id,omitempty"`

	// (Number) The ID of the billing source containing billing data for this account.
	// The ID of the billing source containing billing data for this account.
	PayerID *float64 `json:"payerId,omitempty" tf:"payer_id,omitempty"`

	// (Number) The ID of the Kion project to place this account within.  If empty, the account will be placed within the account cache.
	// The ID of the Kion project to place this account within.  If empty, the account will be placed within the account cache.
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Boolean) True to skip periodic access checking on the account.
	// True to skip periodic access checking on the account.
	SkipAccessChecking *bool `json:"skipAccessChecking,omitempty" tf:"skip_access_checking,omitempty"`

	// MM).  Required if placing an account within a project.
	// Date when the Azure account will starting submitting payments against a funding source (YYYY-MM).  Required if placing an account within a project.
	StartDatecode *string `json:"startDatecode,omitempty" tf:"start_datecode,omitempty"`

	// (String) Name of the subscription as it appears in Azure.
	// Name of the subscription as it appears in Azure.
	SubscriptionName *string `json:"subscriptionName,omitempty" tf:"subscription_name,omitempty"`

	// (String) The UUID of the Azure subscription.  If subscription_uuid is provided, the existing subscription will be imported into Kion.  If subscription_uuid is omitted, a new subscription will be created.
	// The UUID of the Azure subscription.  If subscription_uuid is provided, the existing subscription will be imported into Kion.  If subscription_uuid is omitted, a new subscription will be created.
	SubscriptionUUID *string `json:"subscriptionUuid,omitempty" tf:"subscription_uuid,omitempty"`
}

type AzureAccountMoveProjectSettingsInitParameters struct {

	// (String) One of "move" or "preserve".  If "move", financial history will be moved to the new project beginning on the date specified by the move_datecode parameter.  If "preserve", financial history will be preserved on the current project.
	// One of "move" or "preserve".  If "move", financial history will be moved to the new project beginning on the date specified by the move_datecode parameter.  If "preserve", financial history will be preserved on the current project.
	Financials *string `json:"financials,omitempty" tf:"financials,omitempty"`

	// (Number) The start date to use when moving financial data in YYYYMM format.  This only applies when financials is set to move.  If provided, only financial data from this date to the current month will be moved to the new project.  If omitted or 0, all financial data will be moved to the new project.
	// The start date to use when moving financial data in YYYYMM format.  This only applies when financials is set to move.  If provided, only financial data from this date to the current month will be moved to the new project.  If omitted or 0, all financial data will be moved to the new project.
	MoveDatecode *float64 `json:"moveDatecode,omitempty" tf:"move_datecode,omitempty"`
}

type AzureAccountMoveProjectSettingsObservation struct {

	// (String) One of "move" or "preserve".  If "move", financial history will be moved to the new project beginning on the date specified by the move_datecode parameter.  If "preserve", financial history will be preserved on the current project.
	// One of "move" or "preserve".  If "move", financial history will be moved to the new project beginning on the date specified by the move_datecode parameter.  If "preserve", financial history will be preserved on the current project.
	Financials *string `json:"financials,omitempty" tf:"financials,omitempty"`

	// (Number) The start date to use when moving financial data in YYYYMM format.  This only applies when financials is set to move.  If provided, only financial data from this date to the current month will be moved to the new project.  If omitted or 0, all financial data will be moved to the new project.
	// The start date to use when moving financial data in YYYYMM format.  This only applies when financials is set to move.  If provided, only financial data from this date to the current month will be moved to the new project.  If omitted or 0, all financial data will be moved to the new project.
	MoveDatecode *float64 `json:"moveDatecode,omitempty" tf:"move_datecode,omitempty"`
}

type AzureAccountMoveProjectSettingsParameters struct {

	// (String) One of "move" or "preserve".  If "move", financial history will be moved to the new project beginning on the date specified by the move_datecode parameter.  If "preserve", financial history will be preserved on the current project.
	// One of "move" or "preserve".  If "move", financial history will be moved to the new project beginning on the date specified by the move_datecode parameter.  If "preserve", financial history will be preserved on the current project.
	// +kubebuilder:validation:Optional
	Financials *string `json:"financials,omitempty" tf:"financials,omitempty"`

	// (Number) The start date to use when moving financial data in YYYYMM format.  This only applies when financials is set to move.  If provided, only financial data from this date to the current month will be moved to the new project.  If omitted or 0, all financial data will be moved to the new project.
	// The start date to use when moving financial data in YYYYMM format.  This only applies when financials is set to move.  If provided, only financial data from this date to the current month will be moved to the new project.  If omitted or 0, all financial data will be moved to the new project.
	// +kubebuilder:validation:Optional
	MoveDatecode *float64 `json:"moveDatecode,omitempty" tf:"move_datecode,omitempty"`
}

type AzureAccountObservation struct {

	// (String) Account alias is an optional short unique name that helps identify the account within Kion.
	// Account alias is an optional short unique name that helps identify the account within Kion.
	AccountAlias *string `json:"accountAlias,omitempty" tf:"account_alias,omitempty"`

	// (Number) An ID representing the account type within Kion.
	// An ID representing the account type within Kion.
	AccountTypeID *float64 `json:"accountTypeId,omitempty" tf:"account_type_id,omitempty"`

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Block Set, Max: 1) Parameters used when creating a new Azure CSP subscription. (see below for nested schema)
	// Parameters used when creating a new Azure CSP subscription.
	Csp []CspObservation `json:"csp,omitempty" tf:"csp,omitempty"`

	// (Block Set, Max: 1) Parameters used when creating a new Azure EA subscription. (see below for nested schema)
	// Parameters used when creating a new Azure EA subscription.
	Ea []EaObservation `json:"ea,omitempty" tf:"ea,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of String) A map of labels to assign to the account. The labels must already exist in Kion.
	// A map of labels to assign to the account. The labels must already exist in Kion.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String) Where the account is attached.  Either "project" or "cache".
	// Where the account is attached.  Either "project" or "cache".
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (Block Set, Max: 1) Parameters used when creating a new Azure MCA subscription. (see below for nested schema)
	// Parameters used when creating a new Azure MCA subscription.
	Mca []McaObservation `json:"mca,omitempty" tf:"mca,omitempty"`

	// (Block Set, Max: 1) Parameters used when moving an account between Kion projects.  These settings are ignored unless moving an account. (see below for nested schema)
	// Parameters used when moving an account between Kion projects.  These settings are ignored unless moving an account.
	MoveProjectSettings []AzureAccountMoveProjectSettingsObservation `json:"moveProjectSettings,omitempty" tf:"move_project_settings,omitempty"`

	// (String) The name of the Azure account within Kion.
	// The name of the Azure account within Kion.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The parent management group ID when creating an Azure subscription. If provided, the subscription will be created under the provided management group.  If not provided, the subscription will be created at the root level
	// The parent management group ID when creating an Azure subscription. If provided, the subscription will be created under the provided management group.  If not provided, the subscription will be created at the root level
	ParentManagementGroupID *string `json:"parentManagementGroupId,omitempty" tf:"parent_management_group_id,omitempty"`

	// (Number) The ID of the billing source containing billing data for this account.
	// The ID of the billing source containing billing data for this account.
	PayerID *float64 `json:"payerId,omitempty" tf:"payer_id,omitempty"`

	// (Number) The ID of the Kion project to place this account within.  If empty, the account will be placed within the account cache.
	// The ID of the Kion project to place this account within.  If empty, the account will be placed within the account cache.
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Boolean) True to skip periodic access checking on the account.
	// True to skip periodic access checking on the account.
	SkipAccessChecking *bool `json:"skipAccessChecking,omitempty" tf:"skip_access_checking,omitempty"`

	// MM).  Required if placing an account within a project.
	// Date when the Azure account will starting submitting payments against a funding source (YYYY-MM).  Required if placing an account within a project.
	StartDatecode *string `json:"startDatecode,omitempty" tf:"start_datecode,omitempty"`

	// (String) Name of the subscription as it appears in Azure.
	// Name of the subscription as it appears in Azure.
	SubscriptionName *string `json:"subscriptionName,omitempty" tf:"subscription_name,omitempty"`

	// (String) The UUID of the Azure subscription.  If subscription_uuid is provided, the existing subscription will be imported into Kion.  If subscription_uuid is omitted, a new subscription will be created.
	// The UUID of the Azure subscription.  If subscription_uuid is provided, the existing subscription will be imported into Kion.  If subscription_uuid is omitted, a new subscription will be created.
	SubscriptionUUID *string `json:"subscriptionUuid,omitempty" tf:"subscription_uuid,omitempty"`
}

type AzureAccountParameters struct {

	// (String) Account alias is an optional short unique name that helps identify the account within Kion.
	// Account alias is an optional short unique name that helps identify the account within Kion.
	// +kubebuilder:validation:Optional
	AccountAlias *string `json:"accountAlias,omitempty" tf:"account_alias,omitempty"`

	// (Number) An ID representing the account type within Kion.
	// An ID representing the account type within Kion.
	// +kubebuilder:validation:Optional
	AccountTypeID *float64 `json:"accountTypeId,omitempty" tf:"account_type_id,omitempty"`

	// (Block Set, Max: 1) Parameters used when creating a new Azure CSP subscription. (see below for nested schema)
	// Parameters used when creating a new Azure CSP subscription.
	// +kubebuilder:validation:Optional
	Csp []CspParameters `json:"csp,omitempty" tf:"csp,omitempty"`

	// (Block Set, Max: 1) Parameters used when creating a new Azure EA subscription. (see below for nested schema)
	// Parameters used when creating a new Azure EA subscription.
	// +kubebuilder:validation:Optional
	Ea []EaParameters `json:"ea,omitempty" tf:"ea,omitempty"`

	// (Map of String) A map of labels to assign to the account. The labels must already exist in Kion.
	// A map of labels to assign to the account. The labels must already exist in Kion.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Block Set, Max: 1) Parameters used when creating a new Azure MCA subscription. (see below for nested schema)
	// Parameters used when creating a new Azure MCA subscription.
	// +kubebuilder:validation:Optional
	Mca []McaParameters `json:"mca,omitempty" tf:"mca,omitempty"`

	// (Block Set, Max: 1) Parameters used when moving an account between Kion projects.  These settings are ignored unless moving an account. (see below for nested schema)
	// Parameters used when moving an account between Kion projects.  These settings are ignored unless moving an account.
	// +kubebuilder:validation:Optional
	MoveProjectSettings []AzureAccountMoveProjectSettingsParameters `json:"moveProjectSettings,omitempty" tf:"move_project_settings,omitempty"`

	// (String) The name of the Azure account within Kion.
	// The name of the Azure account within Kion.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The parent management group ID when creating an Azure subscription. If provided, the subscription will be created under the provided management group.  If not provided, the subscription will be created at the root level
	// The parent management group ID when creating an Azure subscription. If provided, the subscription will be created under the provided management group.  If not provided, the subscription will be created at the root level
	// +kubebuilder:validation:Optional
	ParentManagementGroupID *string `json:"parentManagementGroupId,omitempty" tf:"parent_management_group_id,omitempty"`

	// (Number) The ID of the billing source containing billing data for this account.
	// The ID of the billing source containing billing data for this account.
	// +kubebuilder:validation:Optional
	PayerID *float64 `json:"payerId,omitempty" tf:"payer_id,omitempty"`

	// (Number) The ID of the Kion project to place this account within.  If empty, the account will be placed within the account cache.
	// The ID of the Kion project to place this account within.  If empty, the account will be placed within the account cache.
	// +kubebuilder:validation:Optional
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Boolean) True to skip periodic access checking on the account.
	// True to skip periodic access checking on the account.
	// +kubebuilder:validation:Optional
	SkipAccessChecking *bool `json:"skipAccessChecking,omitempty" tf:"skip_access_checking,omitempty"`

	// MM).  Required if placing an account within a project.
	// Date when the Azure account will starting submitting payments against a funding source (YYYY-MM).  Required if placing an account within a project.
	// +kubebuilder:validation:Optional
	StartDatecode *string `json:"startDatecode,omitempty" tf:"start_datecode,omitempty"`

	// (String) Name of the subscription as it appears in Azure.
	// Name of the subscription as it appears in Azure.
	// +kubebuilder:validation:Optional
	SubscriptionName *string `json:"subscriptionName,omitempty" tf:"subscription_name,omitempty"`

	// (String) The UUID of the Azure subscription.  If subscription_uuid is provided, the existing subscription will be imported into Kion.  If subscription_uuid is omitted, a new subscription will be created.
	// The UUID of the Azure subscription.  If subscription_uuid is provided, the existing subscription will be imported into Kion.  If subscription_uuid is omitted, a new subscription will be created.
	// +kubebuilder:validation:Optional
	SubscriptionUUID *string `json:"subscriptionUuid,omitempty" tf:"subscription_uuid,omitempty"`
}

type CspInitParameters struct {

	// (String) Azure CSP billing cycle
	// Azure CSP billing cycle
	BillingCycle *string `json:"billingCycle,omitempty" tf:"billing_cycle,omitempty"`

	// (String) Azure CSP offer id
	// Azure CSP offer id
	OfferID *string `json:"offerId,omitempty" tf:"offer_id,omitempty"`
}

type CspObservation struct {

	// (String) Azure CSP billing cycle
	// Azure CSP billing cycle
	BillingCycle *string `json:"billingCycle,omitempty" tf:"billing_cycle,omitempty"`

	// (String) Azure CSP offer id
	// Azure CSP offer id
	OfferID *string `json:"offerId,omitempty" tf:"offer_id,omitempty"`
}

type CspParameters struct {

	// (String) Azure CSP billing cycle
	// Azure CSP billing cycle
	// +kubebuilder:validation:Optional
	BillingCycle *string `json:"billingCycle,omitempty" tf:"billing_cycle,omitempty"`

	// (String) Azure CSP offer id
	// Azure CSP offer id
	// +kubebuilder:validation:Optional
	OfferID *string `json:"offerId" tf:"offer_id,omitempty"`
}

type EaInitParameters struct {

	// (String) Azure EA account number
	// Azure EA account number
	Account *string `json:"account,omitempty" tf:"account,omitempty"`

	// (String) Azure billing account number
	// Azure billing account number
	BillingAccount *string `json:"billingAccount,omitempty" tf:"billing_account,omitempty"`
}

type EaObservation struct {

	// (String) Azure EA account number
	// Azure EA account number
	Account *string `json:"account,omitempty" tf:"account,omitempty"`

	// (String) Azure billing account number
	// Azure billing account number
	BillingAccount *string `json:"billingAccount,omitempty" tf:"billing_account,omitempty"`
}

type EaParameters struct {

	// (String) Azure EA account number
	// Azure EA account number
	// +kubebuilder:validation:Optional
	Account *string `json:"account" tf:"account,omitempty"`

	// (String) Azure billing account number
	// Azure billing account number
	// +kubebuilder:validation:Optional
	BillingAccount *string `json:"billingAccount" tf:"billing_account,omitempty"`
}

type McaInitParameters struct {

	// (String) Azure billing account number
	// Azure MCA billing account number
	BillingAccount *string `json:"billingAccount,omitempty" tf:"billing_account,omitempty"`

	// (String) Azure MCA billing profile number
	// Azure MCA billing profile number
	BillingProfile *string `json:"billingProfile,omitempty" tf:"billing_profile,omitempty"`

	// (String) Azure MCA billing profile invoice section number
	// Azure MCA billing profile invoice section number
	BillingProfileInvoice *string `json:"billingProfileInvoice,omitempty" tf:"billing_profile_invoice,omitempty"`
}

type McaObservation struct {

	// (String) Azure billing account number
	// Azure MCA billing account number
	BillingAccount *string `json:"billingAccount,omitempty" tf:"billing_account,omitempty"`

	// (String) Azure MCA billing profile number
	// Azure MCA billing profile number
	BillingProfile *string `json:"billingProfile,omitempty" tf:"billing_profile,omitempty"`

	// (String) Azure MCA billing profile invoice section number
	// Azure MCA billing profile invoice section number
	BillingProfileInvoice *string `json:"billingProfileInvoice,omitempty" tf:"billing_profile_invoice,omitempty"`
}

type McaParameters struct {

	// (String) Azure billing account number
	// Azure MCA billing account number
	// +kubebuilder:validation:Optional
	BillingAccount *string `json:"billingAccount" tf:"billing_account,omitempty"`

	// (String) Azure MCA billing profile number
	// Azure MCA billing profile number
	// +kubebuilder:validation:Optional
	BillingProfile *string `json:"billingProfile" tf:"billing_profile,omitempty"`

	// (String) Azure MCA billing profile invoice section number
	// Azure MCA billing profile invoice section number
	// +kubebuilder:validation:Optional
	BillingProfileInvoice *string `json:"billingProfileInvoice" tf:"billing_profile_invoice,omitempty"`
}

// AzureAccountSpec defines the desired state of AzureAccount
type AzureAccountSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AzureAccountParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AzureAccountInitParameters `json:"initProvider,omitempty"`
}

// AzureAccountStatus defines the observed state of AzureAccount.
type AzureAccountStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AzureAccountObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AzureAccount is the Schema for the AzureAccounts API. Creates or imports an Azure Subscription and adds it to a Kion project or the Kion account cache. If subscription_uuid is provided, an existing subscription will be imported into Kion, otherwise a new Azure subscription will be created.  If project_id is provided the account will be added to the corresponding project, otherwise the account will be added to the account cache. Once added, an account can be moved between projects or in and out of the account cache by changing the project_id.  When moving accounts between projects, use move_project_settings to control how financials will be treated between the old and new project.test-cached-account account_cache_id=321
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type AzureAccount struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.payerId) || (has(self.initProvider) && has(self.initProvider.payerId))",message="spec.forProvider.payerId is a required parameter"
	Spec   AzureAccountSpec   `json:"spec"`
	Status AzureAccountStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AzureAccountList contains a list of AzureAccounts
type AzureAccountList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AzureAccount `json:"items"`
}

// Repository type metadata.
var (
	AzureAccount_Kind             = "AzureAccount"
	AzureAccount_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AzureAccount_Kind}.String()
	AzureAccount_KindAPIVersion   = AzureAccount_Kind + "." + CRDGroupVersion.String()
	AzureAccount_GroupVersionKind = CRDGroupVersion.WithKind(AzureAccount_Kind)
)

func init() {
	SchemeBuilder.Register(&AzureAccount{}, &AzureAccountList{})
}
