// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ArmTemplateInitParameters struct {

	// (Number)
	DeploymentMode *float64 `json:"deploymentMode,omitempty" tf:"deployment_mode,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUserGroups []ArmTemplateOwnerUserGroupsInitParameters `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUsers []ArmTemplateOwnerUsersInitParameters `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (String)
	ResourceGroupName *string `json:"resourceGroupName,omitempty" tf:"resource_group_name,omitempty"`

	// (Number)
	ResourceGroupRegionID *float64 `json:"resourceGroupRegionId,omitempty" tf:"resource_group_region_id,omitempty"`

	// (String)
	Template *string `json:"template,omitempty" tf:"template,omitempty"`

	// (String)
	TemplateParameters *string `json:"templateParameters,omitempty" tf:"template_parameters,omitempty"`
}

type ArmTemplateObservation struct {

	// (Boolean)
	CtManaged *bool `json:"ctManaged,omitempty" tf:"ct_managed,omitempty"`

	// (Number)
	DeploymentMode *float64 `json:"deploymentMode,omitempty" tf:"deployment_mode,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUserGroups []ArmTemplateOwnerUserGroupsObservation `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUsers []ArmTemplateOwnerUsersObservation `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (String)
	ResourceGroupName *string `json:"resourceGroupName,omitempty" tf:"resource_group_name,omitempty"`

	// (Number)
	ResourceGroupRegionID *float64 `json:"resourceGroupRegionId,omitempty" tf:"resource_group_region_id,omitempty"`

	// (String)
	Template *string `json:"template,omitempty" tf:"template,omitempty"`

	// (String)
	TemplateParameters *string `json:"templateParameters,omitempty" tf:"template_parameters,omitempty"`

	// (Number)
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

type ArmTemplateOwnerUserGroupsInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ArmTemplateOwnerUserGroupsObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ArmTemplateOwnerUserGroupsParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ArmTemplateOwnerUsersInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ArmTemplateOwnerUsersObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ArmTemplateOwnerUsersParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ArmTemplateParameters struct {

	// (Number)
	// +kubebuilder:validation:Optional
	DeploymentMode *float64 `json:"deploymentMode,omitempty" tf:"deployment_mode,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	// +kubebuilder:validation:Optional
	OwnerUserGroups []ArmTemplateOwnerUserGroupsParameters `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	// +kubebuilder:validation:Optional
	OwnerUsers []ArmTemplateOwnerUsersParameters `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	ResourceGroupName *string `json:"resourceGroupName,omitempty" tf:"resource_group_name,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	ResourceGroupRegionID *float64 `json:"resourceGroupRegionId,omitempty" tf:"resource_group_region_id,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Template *string `json:"template,omitempty" tf:"template,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	TemplateParameters *string `json:"templateParameters,omitempty" tf:"template_parameters,omitempty"`
}

// ArmTemplateSpec defines the desired state of ArmTemplate
type ArmTemplateSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ArmTemplateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ArmTemplateInitParameters `json:"initProvider,omitempty"`
}

// ArmTemplateStatus defines the observed state of ArmTemplate.
type ArmTemplateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ArmTemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ArmTemplate is the Schema for the ArmTemplates API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type ArmTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.deploymentMode) || (has(self.initProvider) && has(self.initProvider.deploymentMode))",message="spec.forProvider.deploymentMode is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.resourceGroupName) || (has(self.initProvider) && has(self.initProvider.resourceGroupName))",message="spec.forProvider.resourceGroupName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.resourceGroupRegionId) || (has(self.initProvider) && has(self.initProvider.resourceGroupRegionId))",message="spec.forProvider.resourceGroupRegionId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.template) || (has(self.initProvider) && has(self.initProvider.template))",message="spec.forProvider.template is a required parameter"
	Spec   ArmTemplateSpec   `json:"spec"`
	Status ArmTemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ArmTemplateList contains a list of ArmTemplates
type ArmTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ArmTemplate `json:"items"`
}

// Repository type metadata.
var (
	ArmTemplate_Kind             = "ArmTemplate"
	ArmTemplate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ArmTemplate_Kind}.String()
	ArmTemplate_KindAPIVersion   = ArmTemplate_Kind + "." + CRDGroupVersion.String()
	ArmTemplate_GroupVersionKind = CRDGroupVersion.WithKind(ArmTemplate_Kind)
)

func init() {
	SchemeBuilder.Register(&ArmTemplate{}, &ArmTemplateList{})
}
