// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AzurePolicyInitParameters struct {
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUserGroups []AzurePolicyOwnerUserGroupsInitParameters `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUsers []AzurePolicyOwnerUsersInitParameters `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	Parameters *string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`
}

type AzurePolicyObservation struct {
	AzureManagedPolicyDefID *string `json:"azureManagedPolicyDefId,omitempty" tf:"azure_managed_policy_def_id,omitempty"`

	CtManaged *bool `json:"ctManaged,omitempty" tf:"ct_managed,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUserGroups []AzurePolicyOwnerUserGroupsObservation `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUsers []AzurePolicyOwnerUsersObservation `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	Parameters *string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`
}

type AzurePolicyOwnerUserGroupsInitParameters struct {
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type AzurePolicyOwnerUserGroupsObservation struct {
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type AzurePolicyOwnerUserGroupsParameters struct {

	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type AzurePolicyOwnerUsersInitParameters struct {
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type AzurePolicyOwnerUsersObservation struct {
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type AzurePolicyOwnerUsersParameters struct {

	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type AzurePolicyParameters struct {

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Must provide at least the owner_user_groups field or the owner_users field.
	// +kubebuilder:validation:Optional
	OwnerUserGroups []AzurePolicyOwnerUserGroupsParameters `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// Must provide at least the owner_user_groups field or the owner_users field.
	// +kubebuilder:validation:Optional
	OwnerUsers []AzurePolicyOwnerUsersParameters `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// +kubebuilder:validation:Optional
	Parameters *string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// +kubebuilder:validation:Optional
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`
}

// AzurePolicySpec defines the desired state of AzurePolicy
type AzurePolicySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AzurePolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AzurePolicyInitParameters `json:"initProvider,omitempty"`
}

// AzurePolicyStatus defines the observed state of AzurePolicy.
type AzurePolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AzurePolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AzurePolicy is the Schema for the AzurePolicys API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type AzurePolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.policy) || (has(self.initProvider) && has(self.initProvider.policy))",message="spec.forProvider.policy is a required parameter"
	Spec   AzurePolicySpec   `json:"spec"`
	Status AzurePolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AzurePolicyList contains a list of AzurePolicys
type AzurePolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AzurePolicy `json:"items"`
}

// Repository type metadata.
var (
	AzurePolicy_Kind             = "AzurePolicy"
	AzurePolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AzurePolicy_Kind}.String()
	AzurePolicy_KindAPIVersion   = AzurePolicy_Kind + "." + CRDGroupVersion.String()
	AzurePolicy_GroupVersionKind = CRDGroupVersion.WithKind(AzurePolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&AzurePolicy{}, &AzurePolicyList{})
}
