// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AWSAccountInitParameters struct {

	// (String) Account alias is an optional short unique name that helps identify the account within Kion.
	// Account alias is an optional short unique name that helps identify the account within Kion.
	AccountAlias *string `json:"accountAlias,omitempty" tf:"account_alias,omitempty"`

	// (String) The account number of the AWS account.  If account_number is provided, the existing account will be imported into Kion.  If account_number is omitted, a new account will be created.
	// The account number of the AWS account.  If account_number is provided, the existing account will be imported into Kion.  If account_number is omitted, a new account will be created.
	AccountNumber *string `json:"accountNumber,omitempty" tf:"account_number,omitempty"`

	// (Number) An ID representing the account type within Kion.
	// An ID representing the account type within Kion.
	AccountTypeID *float64 `json:"accountTypeId,omitempty" tf:"account_type_id,omitempty"`

	// (Block Set, Max: 1) Where to place this account within AWS Organization when creating an account. (see below for nested schema)
	// Where to place this account within AWS Organization when creating an account.
	AwsOrganizationalUnit []AwsOrganizationalUnitInitParameters `json:"awsOrganizationalUnit,omitempty" tf:"aws_organizational_unit,omitempty"`

	// (String) The name used when creating new commercial account.
	// The name used when creating new commercial account.
	CommercialAccountName *string `json:"commercialAccountName,omitempty" tf:"commercial_account_name,omitempty"`

	// (Boolean) True to create an AWS GovCloud account.
	// True to create an AWS GovCloud account.
	CreateGovcloud *bool `json:"createGovcloud,omitempty" tf:"create_govcloud,omitempty"`

	// (String) The root email address to associate with a new account.  Required when creating a new account unless an account placeholder email has been set.
	// The root email address to associate with a new account.  Required when creating a new account unless an account placeholder email has been set.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) The name used when creating new GovCloud account.
	// The name used when creating new GovCloud account.
	GovAccountName *string `json:"govAccountName,omitempty" tf:"gov_account_name,omitempty"`

	// (Boolean) True to associate spend from a linked GovCloud account with this account.
	// True to associate spend from a linked GovCloud account with this account.
	IncludeLinkedAccountSpend *bool `json:"includeLinkedAccountSpend,omitempty" tf:"include_linked_account_spend,omitempty"`

	// (Map of String) A map of labels to assign to the account. The labels must already exist in Kion.
	// A map of labels to assign to the account. The labels must already exist in Kion.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String) The AWS organization service role.
	// The AWS organization service role.
	LinkedRole *string `json:"linkedRole,omitempty" tf:"linked_role,omitempty"`

	// (Block Set, Max: 1) Parameters used when moving an account between Kion projects.  These settings are ignored unless moving an account. (see below for nested schema)
	// Parameters used when moving an account between Kion projects.  These settings are ignored unless moving an account.
	MoveProjectSettings []MoveProjectSettingsInitParameters `json:"moveProjectSettings,omitempty" tf:"move_project_settings,omitempty"`

	// (String) The name of the AWS account within Kion.
	// The name of the AWS account within Kion.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The ID of the billing source containing billing data for this account.
	// The ID of the billing source containing billing data for this account.
	PayerID *float64 `json:"payerId,omitempty" tf:"payer_id,omitempty"`

	// (Number) The ID of the Kion project to place this account within.  If empty, the account will be placed within the account cache.
	// The ID of the Kion project to place this account within.  If empty, the account will be placed within the account cache.
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Boolean) True to skip periodic access checking on the account.
	// True to skip periodic access checking on the account.
	SkipAccessChecking *bool `json:"skipAccessChecking,omitempty" tf:"skip_access_checking,omitempty"`

	// MM).  Required if placing an account within a project.
	// Date when the AWS account will starting submitting payments against a funding source (YYYY-MM).  Required if placing an account within a project.
	StartDatecode *string `json:"startDatecode,omitempty" tf:"start_datecode,omitempty"`

	// (Boolean) True to keep the account name and email address in Kion in sync with the account name and email address as set in AWS Organization.
	// True to keep the account name and email address in Kion in sync with the account name and email address as set in AWS Organization.
	UseOrgAccountInfo *bool `json:"useOrgAccountInfo,omitempty" tf:"use_org_account_info,omitempty"`
}

type AWSAccountObservation struct {

	// (String) Account alias is an optional short unique name that helps identify the account within Kion.
	// Account alias is an optional short unique name that helps identify the account within Kion.
	AccountAlias *string `json:"accountAlias,omitempty" tf:"account_alias,omitempty"`

	// (String) The account number of the AWS account.  If account_number is provided, the existing account will be imported into Kion.  If account_number is omitted, a new account will be created.
	// The account number of the AWS account.  If account_number is provided, the existing account will be imported into Kion.  If account_number is omitted, a new account will be created.
	AccountNumber *string `json:"accountNumber,omitempty" tf:"account_number,omitempty"`

	// (Number) An ID representing the account type within Kion.
	// An ID representing the account type within Kion.
	AccountTypeID *float64 `json:"accountTypeId,omitempty" tf:"account_type_id,omitempty"`

	// (Block Set, Max: 1) Where to place this account within AWS Organization when creating an account. (see below for nested schema)
	// Where to place this account within AWS Organization when creating an account.
	AwsOrganizationalUnit []AwsOrganizationalUnitObservation `json:"awsOrganizationalUnit,omitempty" tf:"aws_organizational_unit,omitempty"`

	// (String) The external ID used when assuming cloud access roles.
	// The external ID used when assuming cloud access roles.
	CarExternalID *string `json:"carExternalId,omitempty" tf:"car_external_id,omitempty"`

	// (String) The name used when creating new commercial account.
	// The name used when creating new commercial account.
	CommercialAccountName *string `json:"commercialAccountName,omitempty" tf:"commercial_account_name,omitempty"`

	// (Boolean) True to create an AWS GovCloud account.
	// True to create an AWS GovCloud account.
	CreateGovcloud *bool `json:"createGovcloud,omitempty" tf:"create_govcloud,omitempty"`

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) The root email address to associate with a new account.  Required when creating a new account unless an account placeholder email has been set.
	// The root email address to associate with a new account.  Required when creating a new account unless an account placeholder email has been set.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) The name used when creating new GovCloud account.
	// The name used when creating new GovCloud account.
	GovAccountName *string `json:"govAccountName,omitempty" tf:"gov_account_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) True to associate spend from a linked GovCloud account with this account.
	// True to associate spend from a linked GovCloud account with this account.
	IncludeLinkedAccountSpend *bool `json:"includeLinkedAccountSpend,omitempty" tf:"include_linked_account_spend,omitempty"`

	// (Map of String) A map of labels to assign to the account. The labels must already exist in Kion.
	// A map of labels to assign to the account. The labels must already exist in Kion.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String) For AWS GovCloud accounts, this is the linked commercial account.  Otherwise this is empty.
	// For AWS GovCloud accounts, this is the linked commercial account.  Otherwise this is empty.
	LinkedAccountNumber *string `json:"linkedAccountNumber,omitempty" tf:"linked_account_number,omitempty"`

	// (String) The AWS organization service role.
	// The AWS organization service role.
	LinkedRole *string `json:"linkedRole,omitempty" tf:"linked_role,omitempty"`

	// (String) Where the account is attached.  Either "project" or "cache".
	// Where the account is attached.  Either "project" or "cache".
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (Block Set, Max: 1) Parameters used when moving an account between Kion projects.  These settings are ignored unless moving an account. (see below for nested schema)
	// Parameters used when moving an account between Kion projects.  These settings are ignored unless moving an account.
	MoveProjectSettings []MoveProjectSettingsObservation `json:"moveProjectSettings,omitempty" tf:"move_project_settings,omitempty"`

	// (String) The name of the AWS account within Kion.
	// The name of the AWS account within Kion.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The ID of the billing source containing billing data for this account.
	// The ID of the billing source containing billing data for this account.
	PayerID *float64 `json:"payerId,omitempty" tf:"payer_id,omitempty"`

	// (Number) The ID of the Kion project to place this account within.  If empty, the account will be placed within the account cache.
	// The ID of the Kion project to place this account within.  If empty, the account will be placed within the account cache.
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The external ID used for automated internal actions using the service role for this account.
	// The external ID used for automated internal actions using the service role for this account.
	ServiceExternalID *string `json:"serviceExternalId,omitempty" tf:"service_external_id,omitempty"`

	// (Boolean) True to skip periodic access checking on the account.
	// True to skip periodic access checking on the account.
	SkipAccessChecking *bool `json:"skipAccessChecking,omitempty" tf:"skip_access_checking,omitempty"`

	// MM).  Required if placing an account within a project.
	// Date when the AWS account will starting submitting payments against a funding source (YYYY-MM).  Required if placing an account within a project.
	StartDatecode *string `json:"startDatecode,omitempty" tf:"start_datecode,omitempty"`

	// (Boolean) True to keep the account name and email address in Kion in sync with the account name and email address as set in AWS Organization.
	// True to keep the account name and email address in Kion in sync with the account name and email address as set in AWS Organization.
	UseOrgAccountInfo *bool `json:"useOrgAccountInfo,omitempty" tf:"use_org_account_info,omitempty"`
}

type AWSAccountParameters struct {

	// (String) Account alias is an optional short unique name that helps identify the account within Kion.
	// Account alias is an optional short unique name that helps identify the account within Kion.
	// +kubebuilder:validation:Optional
	AccountAlias *string `json:"accountAlias,omitempty" tf:"account_alias,omitempty"`

	// (String) The account number of the AWS account.  If account_number is provided, the existing account will be imported into Kion.  If account_number is omitted, a new account will be created.
	// The account number of the AWS account.  If account_number is provided, the existing account will be imported into Kion.  If account_number is omitted, a new account will be created.
	// +kubebuilder:validation:Optional
	AccountNumber *string `json:"accountNumber,omitempty" tf:"account_number,omitempty"`

	// (Number) An ID representing the account type within Kion.
	// An ID representing the account type within Kion.
	// +kubebuilder:validation:Optional
	AccountTypeID *float64 `json:"accountTypeId,omitempty" tf:"account_type_id,omitempty"`

	// (Block Set, Max: 1) Where to place this account within AWS Organization when creating an account. (see below for nested schema)
	// Where to place this account within AWS Organization when creating an account.
	// +kubebuilder:validation:Optional
	AwsOrganizationalUnit []AwsOrganizationalUnitParameters `json:"awsOrganizationalUnit,omitempty" tf:"aws_organizational_unit,omitempty"`

	// (String) The name used when creating new commercial account.
	// The name used when creating new commercial account.
	// +kubebuilder:validation:Optional
	CommercialAccountName *string `json:"commercialAccountName,omitempty" tf:"commercial_account_name,omitempty"`

	// (Boolean) True to create an AWS GovCloud account.
	// True to create an AWS GovCloud account.
	// +kubebuilder:validation:Optional
	CreateGovcloud *bool `json:"createGovcloud,omitempty" tf:"create_govcloud,omitempty"`

	// (String) The root email address to associate with a new account.  Required when creating a new account unless an account placeholder email has been set.
	// The root email address to associate with a new account.  Required when creating a new account unless an account placeholder email has been set.
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) The name used when creating new GovCloud account.
	// The name used when creating new GovCloud account.
	// +kubebuilder:validation:Optional
	GovAccountName *string `json:"govAccountName,omitempty" tf:"gov_account_name,omitempty"`

	// (Boolean) True to associate spend from a linked GovCloud account with this account.
	// True to associate spend from a linked GovCloud account with this account.
	// +kubebuilder:validation:Optional
	IncludeLinkedAccountSpend *bool `json:"includeLinkedAccountSpend,omitempty" tf:"include_linked_account_spend,omitempty"`

	// (Map of String) A map of labels to assign to the account. The labels must already exist in Kion.
	// A map of labels to assign to the account. The labels must already exist in Kion.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String) The AWS organization service role.
	// The AWS organization service role.
	// +kubebuilder:validation:Optional
	LinkedRole *string `json:"linkedRole,omitempty" tf:"linked_role,omitempty"`

	// (Block Set, Max: 1) Parameters used when moving an account between Kion projects.  These settings are ignored unless moving an account. (see below for nested schema)
	// Parameters used when moving an account between Kion projects.  These settings are ignored unless moving an account.
	// +kubebuilder:validation:Optional
	MoveProjectSettings []MoveProjectSettingsParameters `json:"moveProjectSettings,omitempty" tf:"move_project_settings,omitempty"`

	// (String) The name of the AWS account within Kion.
	// The name of the AWS account within Kion.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The ID of the billing source containing billing data for this account.
	// The ID of the billing source containing billing data for this account.
	// +kubebuilder:validation:Optional
	PayerID *float64 `json:"payerId,omitempty" tf:"payer_id,omitempty"`

	// (Number) The ID of the Kion project to place this account within.  If empty, the account will be placed within the account cache.
	// The ID of the Kion project to place this account within.  If empty, the account will be placed within the account cache.
	// +kubebuilder:validation:Optional
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Boolean) True to skip periodic access checking on the account.
	// True to skip periodic access checking on the account.
	// +kubebuilder:validation:Optional
	SkipAccessChecking *bool `json:"skipAccessChecking,omitempty" tf:"skip_access_checking,omitempty"`

	// MM).  Required if placing an account within a project.
	// Date when the AWS account will starting submitting payments against a funding source (YYYY-MM).  Required if placing an account within a project.
	// +kubebuilder:validation:Optional
	StartDatecode *string `json:"startDatecode,omitempty" tf:"start_datecode,omitempty"`

	// (Boolean) True to keep the account name and email address in Kion in sync with the account name and email address as set in AWS Organization.
	// True to keep the account name and email address in Kion in sync with the account name and email address as set in AWS Organization.
	// +kubebuilder:validation:Optional
	UseOrgAccountInfo *bool `json:"useOrgAccountInfo,omitempty" tf:"use_org_account_info,omitempty"`
}

type AwsOrganizationalUnitInitParameters struct {

	// (String) The name of the AWS account within Kion.
	// Name of the organizational unit in AWS.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) OUID of the AWS Organization unit.
	// OUID of the AWS Organization unit.
	OrgUnitID *string `json:"orgUnitId,omitempty" tf:"org_unit_id,omitempty"`
}

type AwsOrganizationalUnitObservation struct {

	// (String) The name of the AWS account within Kion.
	// Name of the organizational unit in AWS.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) OUID of the AWS Organization unit.
	// OUID of the AWS Organization unit.
	OrgUnitID *string `json:"orgUnitId,omitempty" tf:"org_unit_id,omitempty"`
}

type AwsOrganizationalUnitParameters struct {

	// (String) The name of the AWS account within Kion.
	// Name of the organizational unit in AWS.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (String) OUID of the AWS Organization unit.
	// OUID of the AWS Organization unit.
	// +kubebuilder:validation:Optional
	OrgUnitID *string `json:"orgUnitId" tf:"org_unit_id,omitempty"`
}

type MoveProjectSettingsInitParameters struct {

	// (String) One of "move" or "preserve".  If "move", financial history will be moved to the new project beginning on the date specified by the move_datecode parameter.  If "preserve", financial history will be preserved on the current project.
	// One of "move" or "preserve".  If "move", financial history will be moved to the new project beginning on the date specified by the move_datecode parameter.  If "preserve", financial history will be preserved on the current project.
	Financials *string `json:"financials,omitempty" tf:"financials,omitempty"`

	// (Number) The start date to use when moving financial data in YYYYMM format.  This only applies when financials is set to move.  If provided, only financial data from this date to the current month will be moved to the new project.  If omitted or 0, all financial data will be moved to the new project.
	// The start date to use when moving financial data in YYYYMM format.  This only applies when financials is set to move.  If provided, only financial data from this date to the current month will be moved to the new project.  If omitted or 0, all financial data will be moved to the new project.
	MoveDatecode *float64 `json:"moveDatecode,omitempty" tf:"move_datecode,omitempty"`
}

type MoveProjectSettingsObservation struct {

	// (String) One of "move" or "preserve".  If "move", financial history will be moved to the new project beginning on the date specified by the move_datecode parameter.  If "preserve", financial history will be preserved on the current project.
	// One of "move" or "preserve".  If "move", financial history will be moved to the new project beginning on the date specified by the move_datecode parameter.  If "preserve", financial history will be preserved on the current project.
	Financials *string `json:"financials,omitempty" tf:"financials,omitempty"`

	// (Number) The start date to use when moving financial data in YYYYMM format.  This only applies when financials is set to move.  If provided, only financial data from this date to the current month will be moved to the new project.  If omitted or 0, all financial data will be moved to the new project.
	// The start date to use when moving financial data in YYYYMM format.  This only applies when financials is set to move.  If provided, only financial data from this date to the current month will be moved to the new project.  If omitted or 0, all financial data will be moved to the new project.
	MoveDatecode *float64 `json:"moveDatecode,omitempty" tf:"move_datecode,omitempty"`
}

type MoveProjectSettingsParameters struct {

	// (String) One of "move" or "preserve".  If "move", financial history will be moved to the new project beginning on the date specified by the move_datecode parameter.  If "preserve", financial history will be preserved on the current project.
	// One of "move" or "preserve".  If "move", financial history will be moved to the new project beginning on the date specified by the move_datecode parameter.  If "preserve", financial history will be preserved on the current project.
	// +kubebuilder:validation:Optional
	Financials *string `json:"financials,omitempty" tf:"financials,omitempty"`

	// (Number) The start date to use when moving financial data in YYYYMM format.  This only applies when financials is set to move.  If provided, only financial data from this date to the current month will be moved to the new project.  If omitted or 0, all financial data will be moved to the new project.
	// The start date to use when moving financial data in YYYYMM format.  This only applies when financials is set to move.  If provided, only financial data from this date to the current month will be moved to the new project.  If omitted or 0, all financial data will be moved to the new project.
	// +kubebuilder:validation:Optional
	MoveDatecode *float64 `json:"moveDatecode,omitempty" tf:"move_datecode,omitempty"`
}

// AWSAccountSpec defines the desired state of AWSAccount
type AWSAccountSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AWSAccountParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AWSAccountInitParameters `json:"initProvider,omitempty"`
}

// AWSAccountStatus defines the observed state of AWSAccount.
type AWSAccountStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AWSAccountObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AWSAccount is the Schema for the AWSAccounts API. Creates or imports an AWS Account and adds it to a Kion project or the Kion account cache. If account_number is provided, an existing account will be imported into Kion, otherwise a new AWS account will be created.  If project_id is provided the account will be added to the corresponding project, otherwise the account will be added to the account cache. Once added, an account can be moved between projects or in and out of the account cache by changing the project_id.  When moving accounts between projects, use move_project_settings to control how financials will be treated between the old and new project.test-cached-account account_cache_id=321
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type AWSAccount struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.payerId) || (has(self.initProvider) && has(self.initProvider.payerId))",message="spec.forProvider.payerId is a required parameter"
	Spec   AWSAccountSpec   `json:"spec"`
	Status AWSAccountStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AWSAccountList contains a list of AWSAccounts
type AWSAccountList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AWSAccount `json:"items"`
}

// Repository type metadata.
var (
	AWSAccount_Kind             = "AWSAccount"
	AWSAccount_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AWSAccount_Kind}.String()
	AWSAccount_KindAPIVersion   = AWSAccount_Kind + "." + CRDGroupVersion.String()
	AWSAccount_GroupVersionKind = CRDGroupVersion.WithKind(AWSAccount_Kind)
)

func init() {
	SchemeBuilder.Register(&AWSAccount{}, &AWSAccountList{})
}
