// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ComplianceCheckInitParameters struct {

	// (Number)
	AzurePolicyID *float64 `json:"azurePolicyId,omitempty" tf:"azure_policy_id,omitempty"`

	// (String)
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// (Number)
	CloudProviderID *float64 `json:"cloudProviderId,omitempty" tf:"cloud_provider_id,omitempty"`

	// (Number)
	ComplianceCheckTypeID *float64 `json:"complianceCheckTypeId,omitempty" tf:"compliance_check_type_id,omitempty"`

	// (Number)
	CreatedByUserID *float64 `json:"createdByUserId,omitempty" tf:"created_by_user_id,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number)
	FrequencyMinutes *float64 `json:"frequencyMinutes,omitempty" tf:"frequency_minutes,omitempty"`

	// (Number)
	FrequencyTypeID *float64 `json:"frequencyTypeId,omitempty" tf:"frequency_type_id,omitempty"`

	// (Boolean)
	IsAllRegions *bool `json:"isAllRegions,omitempty" tf:"is_all_regions,omitempty"`

	// (Boolean)
	IsAutoArchived *bool `json:"isAutoArchived,omitempty" tf:"is_auto_archived,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUserGroups []ComplianceCheckOwnerUserGroupsInitParameters `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUsers []ComplianceCheckOwnerUsersInitParameters `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (Set of String)
	// +listType=set
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// (Number)
	SeverityTypeID *float64 `json:"severityTypeId,omitempty" tf:"severity_type_id,omitempty"`
}

type ComplianceCheckObservation struct {

	// (Number)
	AzurePolicyID *float64 `json:"azurePolicyId,omitempty" tf:"azure_policy_id,omitempty"`

	// (String)
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// (Number)
	CloudProviderID *float64 `json:"cloudProviderId,omitempty" tf:"cloud_provider_id,omitempty"`

	// (Number)
	ComplianceCheckTypeID *float64 `json:"complianceCheckTypeId,omitempty" tf:"compliance_check_type_id,omitempty"`

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Number)
	CreatedByUserID *float64 `json:"createdByUserId,omitempty" tf:"created_by_user_id,omitempty"`

	// (Boolean)
	CtManaged *bool `json:"ctManaged,omitempty" tf:"ct_managed,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number)
	FrequencyMinutes *float64 `json:"frequencyMinutes,omitempty" tf:"frequency_minutes,omitempty"`

	// (Number)
	FrequencyTypeID *float64 `json:"frequencyTypeId,omitempty" tf:"frequency_type_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean)
	IsAllRegions *bool `json:"isAllRegions,omitempty" tf:"is_all_regions,omitempty"`

	// (Boolean)
	IsAutoArchived *bool `json:"isAutoArchived,omitempty" tf:"is_auto_archived,omitempty"`

	// (Number)
	LastScanID *float64 `json:"lastScanId,omitempty" tf:"last_scan_id,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUserGroups []ComplianceCheckOwnerUserGroupsObservation `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUsers []ComplianceCheckOwnerUsersObservation `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (Set of String)
	// +listType=set
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// (Number)
	SeverityTypeID *float64 `json:"severityTypeId,omitempty" tf:"severity_type_id,omitempty"`
}

type ComplianceCheckOwnerUserGroupsInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ComplianceCheckOwnerUserGroupsObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ComplianceCheckOwnerUserGroupsParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ComplianceCheckOwnerUsersInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ComplianceCheckOwnerUsersObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ComplianceCheckOwnerUsersParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ComplianceCheckParameters struct {

	// (Number)
	// +kubebuilder:validation:Optional
	AzurePolicyID *float64 `json:"azurePolicyId,omitempty" tf:"azure_policy_id,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	CloudProviderID *float64 `json:"cloudProviderId,omitempty" tf:"cloud_provider_id,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	ComplianceCheckTypeID *float64 `json:"complianceCheckTypeId,omitempty" tf:"compliance_check_type_id,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	CreatedByUserID *float64 `json:"createdByUserId,omitempty" tf:"created_by_user_id,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	FrequencyMinutes *float64 `json:"frequencyMinutes,omitempty" tf:"frequency_minutes,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	FrequencyTypeID *float64 `json:"frequencyTypeId,omitempty" tf:"frequency_type_id,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	IsAllRegions *bool `json:"isAllRegions,omitempty" tf:"is_all_regions,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	IsAutoArchived *bool `json:"isAutoArchived,omitempty" tf:"is_auto_archived,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	// +kubebuilder:validation:Optional
	OwnerUserGroups []ComplianceCheckOwnerUserGroupsParameters `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	// +kubebuilder:validation:Optional
	OwnerUsers []ComplianceCheckOwnerUsersParameters `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (Set of String)
	// +kubebuilder:validation:Optional
	// +listType=set
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	SeverityTypeID *float64 `json:"severityTypeId,omitempty" tf:"severity_type_id,omitempty"`
}

// ComplianceCheckSpec defines the desired state of ComplianceCheck
type ComplianceCheckSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ComplianceCheckParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ComplianceCheckInitParameters `json:"initProvider,omitempty"`
}

// ComplianceCheckStatus defines the observed state of ComplianceCheck.
type ComplianceCheckStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ComplianceCheckObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ComplianceCheck is the Schema for the ComplianceChecks API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type ComplianceCheck struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cloudProviderId) || (has(self.initProvider) && has(self.initProvider.cloudProviderId))",message="spec.forProvider.cloudProviderId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.complianceCheckTypeId) || (has(self.initProvider) && has(self.initProvider.complianceCheckTypeId))",message="spec.forProvider.complianceCheckTypeId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ComplianceCheckSpec   `json:"spec"`
	Status ComplianceCheckStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ComplianceCheckList contains a list of ComplianceChecks
type ComplianceCheckList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ComplianceCheck `json:"items"`
}

// Repository type metadata.
var (
	ComplianceCheck_Kind             = "ComplianceCheck"
	ComplianceCheck_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ComplianceCheck_Kind}.String()
	ComplianceCheck_KindAPIVersion   = ComplianceCheck_Kind + "." + CRDGroupVersion.String()
	ComplianceCheck_GroupVersionKind = CRDGroupVersion.WithKind(ComplianceCheck_Kind)
)

func init() {
	SchemeBuilder.Register(&ComplianceCheck{}, &ComplianceCheckList{})
}
