// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CloudFormationTemplateInitParameters struct {

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUserGroups []OwnerUserGroupsInitParameters `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUsers []OwnerUsersInitParameters `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (String)
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// (String)
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Set of String)
	// +listType=set
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// (String)
	SnsArns *string `json:"snsArns,omitempty" tf:"sns_arns,omitempty"`

	// level tags will apply to all supported resources in a CloudFormation stack.  Requires Kion >= 3.7.1.
	// Stack-level tags will apply to all supported resources in a CloudFormation stack.  Requires Kion >= 3.7.1.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String)
	TemplateParameters *string `json:"templateParameters,omitempty" tf:"template_parameters,omitempty"`

	// (Boolean)
	TerminationProtection *bool `json:"terminationProtection,omitempty" tf:"termination_protection,omitempty"`
}

type CloudFormationTemplateObservation struct {

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUserGroups []OwnerUserGroupsObservation `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUsers []OwnerUsersObservation `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (String)
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// (String)
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Set of String)
	// +listType=set
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// (String)
	SnsArns *string `json:"snsArns,omitempty" tf:"sns_arns,omitempty"`

	// level tags will apply to all supported resources in a CloudFormation stack.  Requires Kion >= 3.7.1.
	// Stack-level tags will apply to all supported resources in a CloudFormation stack.  Requires Kion >= 3.7.1.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String)
	TemplateParameters *string `json:"templateParameters,omitempty" tf:"template_parameters,omitempty"`

	// (Boolean)
	TerminationProtection *bool `json:"terminationProtection,omitempty" tf:"termination_protection,omitempty"`
}

type CloudFormationTemplateParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	// +kubebuilder:validation:Optional
	OwnerUserGroups []OwnerUserGroupsParameters `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	// +kubebuilder:validation:Optional
	OwnerUsers []OwnerUsersParameters `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Set of String)
	// +kubebuilder:validation:Optional
	// +listType=set
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	SnsArns *string `json:"snsArns,omitempty" tf:"sns_arns,omitempty"`

	// level tags will apply to all supported resources in a CloudFormation stack.  Requires Kion >= 3.7.1.
	// Stack-level tags will apply to all supported resources in a CloudFormation stack.  Requires Kion >= 3.7.1.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	TemplateParameters *string `json:"templateParameters,omitempty" tf:"template_parameters,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	TerminationProtection *bool `json:"terminationProtection,omitempty" tf:"termination_protection,omitempty"`
}

type OwnerUserGroupsInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type OwnerUserGroupsObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type OwnerUserGroupsParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type OwnerUsersInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type OwnerUsersObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type OwnerUsersParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

// CloudFormationTemplateSpec defines the desired state of CloudFormationTemplate
type CloudFormationTemplateSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CloudFormationTemplateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CloudFormationTemplateInitParameters `json:"initProvider,omitempty"`
}

// CloudFormationTemplateStatus defines the observed state of CloudFormationTemplate.
type CloudFormationTemplateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CloudFormationTemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CloudFormationTemplate is the Schema for the CloudFormationTemplates API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type CloudFormationTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.policy) || (has(self.initProvider) && has(self.initProvider.policy))",message="spec.forProvider.policy is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.regions) || (has(self.initProvider) && has(self.initProvider.regions))",message="spec.forProvider.regions is a required parameter"
	Spec   CloudFormationTemplateSpec   `json:"spec"`
	Status CloudFormationTemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CloudFormationTemplateList contains a list of CloudFormationTemplates
type CloudFormationTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CloudFormationTemplate `json:"items"`
}

// Repository type metadata.
var (
	CloudFormationTemplate_Kind             = "CloudFormationTemplate"
	CloudFormationTemplate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CloudFormationTemplate_Kind}.String()
	CloudFormationTemplate_KindAPIVersion   = CloudFormationTemplate_Kind + "." + CRDGroupVersion.String()
	CloudFormationTemplate_GroupVersionKind = CRDGroupVersion.WithKind(CloudFormationTemplate_Kind)
)

func init() {
	SchemeBuilder.Register(&CloudFormationTemplate{}, &CloudFormationTemplateList{})
}
