// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type FundingSourceInitParameters struct {

	// (Number)
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	EndDatecode *string `json:"endDatecode,omitempty" tf:"end_datecode,omitempty"`

	// (Map of String) A map of labels to assign to the funding source. The labels must already exist in Kion.
	// A map of labels to assign to the funding source. The labels must already exist in Kion.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number)
	OuID *float64 `json:"ouId,omitempty" tf:"ou_id,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUserGroups []FundingSourceOwnerUserGroupsInitParameters `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUsers []FundingSourceOwnerUsersInitParameters `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (Number)
	PermissionSchemeID *float64 `json:"permissionSchemeId,omitempty" tf:"permission_scheme_id,omitempty"`

	// (String)
	StartDatecode *string `json:"startDatecode,omitempty" tf:"start_datecode,omitempty"`
}

type FundingSourceObservation struct {

	// (Number)
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	EndDatecode *string `json:"endDatecode,omitempty" tf:"end_datecode,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of String) A map of labels to assign to the funding source. The labels must already exist in Kion.
	// A map of labels to assign to the funding source. The labels must already exist in Kion.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number)
	OuID *float64 `json:"ouId,omitempty" tf:"ou_id,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUserGroups []FundingSourceOwnerUserGroupsObservation `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUsers []FundingSourceOwnerUsersObservation `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (Number)
	PermissionSchemeID *float64 `json:"permissionSchemeId,omitempty" tf:"permission_scheme_id,omitempty"`

	// (String)
	StartDatecode *string `json:"startDatecode,omitempty" tf:"start_datecode,omitempty"`
}

type FundingSourceOwnerUserGroupsInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type FundingSourceOwnerUserGroupsObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type FundingSourceOwnerUserGroupsParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type FundingSourceOwnerUsersInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type FundingSourceOwnerUsersObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type FundingSourceOwnerUsersParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type FundingSourceParameters struct {

	// (Number)
	// +kubebuilder:validation:Optional
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	EndDatecode *string `json:"endDatecode,omitempty" tf:"end_datecode,omitempty"`

	// (Map of String) A map of labels to assign to the funding source. The labels must already exist in Kion.
	// A map of labels to assign to the funding source. The labels must already exist in Kion.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	OuID *float64 `json:"ouId,omitempty" tf:"ou_id,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	// +kubebuilder:validation:Optional
	OwnerUserGroups []FundingSourceOwnerUserGroupsParameters `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	// +kubebuilder:validation:Optional
	OwnerUsers []FundingSourceOwnerUsersParameters `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	PermissionSchemeID *float64 `json:"permissionSchemeId,omitempty" tf:"permission_scheme_id,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	StartDatecode *string `json:"startDatecode,omitempty" tf:"start_datecode,omitempty"`
}

// FundingSourceSpec defines the desired state of FundingSource
type FundingSourceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FundingSourceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FundingSourceInitParameters `json:"initProvider,omitempty"`
}

// FundingSourceStatus defines the observed state of FundingSource.
type FundingSourceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FundingSourceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FundingSource is the Schema for the FundingSources API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type FundingSource struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.amount) || (has(self.initProvider) && has(self.initProvider.amount))",message="spec.forProvider.amount is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.endDatecode) || (has(self.initProvider) && has(self.initProvider.endDatecode))",message="spec.forProvider.endDatecode is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.permissionSchemeId) || (has(self.initProvider) && has(self.initProvider.permissionSchemeId))",message="spec.forProvider.permissionSchemeId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.startDatecode) || (has(self.initProvider) && has(self.initProvider.startDatecode))",message="spec.forProvider.startDatecode is a required parameter"
	Spec   FundingSourceSpec   `json:"spec"`
	Status FundingSourceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FundingSourceList contains a list of FundingSources
type FundingSourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FundingSource `json:"items"`
}

// Repository type metadata.
var (
	FundingSource_Kind             = "FundingSource"
	FundingSource_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FundingSource_Kind}.String()
	FundingSource_KindAPIVersion   = FundingSource_Kind + "." + CRDGroupVersion.String()
	FundingSource_GroupVersionKind = CRDGroupVersion.WithKind(FundingSource_Kind)
)

func init() {
	SchemeBuilder.Register(&FundingSource{}, &FundingSourceList{})
}
