// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Account) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ArmTemplate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Check) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CloudAccessRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CloudFormationTemplate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ControlPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Enforcement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Group) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GroupAssociation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IAMPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IAMRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Label) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Ou) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PermissionMapping) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Policy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Project) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Role) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Rule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Source) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SourcePermissionMapping) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Standard) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Webhook) Hub() {}
