// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type GCPIAMRoleInitParameters struct {

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number)
	GCPRoleLaunchStage *float64 `json:"gcpRoleLaunchStage,omitempty" tf:"gcp_role_launch_stage,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUserGroups []GCPIAMRoleOwnerUserGroupsInitParameters `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUsers []GCPIAMRoleOwnerUsersInitParameters `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (Set of String)
	// +listType=set
	RolePermissions []*string `json:"rolePermissions,omitempty" tf:"role_permissions,omitempty"`

	// (Boolean)
	SystemManagedPolicy *bool `json:"systemManagedPolicy,omitempty" tf:"system_managed_policy,omitempty"`
}

type GCPIAMRoleObservation struct {

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	GCPID *string `json:"gcpId,omitempty" tf:"gcp_id,omitempty"`

	// (Boolean)
	GCPManagedPolicy *bool `json:"gcpManagedPolicy,omitempty" tf:"gcp_managed_policy,omitempty"`

	// (Number)
	GCPRoleLaunchStage *float64 `json:"gcpRoleLaunchStage,omitempty" tf:"gcp_role_launch_stage,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUserGroups []GCPIAMRoleOwnerUserGroupsObservation `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUsers []GCPIAMRoleOwnerUsersObservation `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (Set of String)
	// +listType=set
	RolePermissions []*string `json:"rolePermissions,omitempty" tf:"role_permissions,omitempty"`

	// (Boolean)
	SystemManagedPolicy *bool `json:"systemManagedPolicy,omitempty" tf:"system_managed_policy,omitempty"`
}

type GCPIAMRoleOwnerUserGroupsInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type GCPIAMRoleOwnerUserGroupsObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type GCPIAMRoleOwnerUserGroupsParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type GCPIAMRoleOwnerUsersInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type GCPIAMRoleOwnerUsersObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type GCPIAMRoleOwnerUsersParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type GCPIAMRoleParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	GCPRoleLaunchStage *float64 `json:"gcpRoleLaunchStage,omitempty" tf:"gcp_role_launch_stage,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	// +kubebuilder:validation:Optional
	OwnerUserGroups []GCPIAMRoleOwnerUserGroupsParameters `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	// +kubebuilder:validation:Optional
	OwnerUsers []GCPIAMRoleOwnerUsersParameters `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (Set of String)
	// +kubebuilder:validation:Optional
	// +listType=set
	RolePermissions []*string `json:"rolePermissions,omitempty" tf:"role_permissions,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	SystemManagedPolicy *bool `json:"systemManagedPolicy,omitempty" tf:"system_managed_policy,omitempty"`
}

// GCPIAMRoleSpec defines the desired state of GCPIAMRole
type GCPIAMRoleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GCPIAMRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GCPIAMRoleInitParameters `json:"initProvider,omitempty"`
}

// GCPIAMRoleStatus defines the observed state of GCPIAMRole.
type GCPIAMRoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GCPIAMRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GCPIAMRole is the Schema for the GCPIAMRoles API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type GCPIAMRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.gcpRoleLaunchStage) || (has(self.initProvider) && has(self.initProvider.gcpRoleLaunchStage))",message="spec.forProvider.gcpRoleLaunchStage is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.rolePermissions) || (has(self.initProvider) && has(self.initProvider.rolePermissions))",message="spec.forProvider.rolePermissions is a required parameter"
	Spec   GCPIAMRoleSpec   `json:"spec"`
	Status GCPIAMRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GCPIAMRoleList contains a list of GCPIAMRoles
type GCPIAMRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GCPIAMRole `json:"items"`
}

// Repository type metadata.
var (
	GCPIAMRole_Kind             = "GCPIAMRole"
	GCPIAMRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GCPIAMRole_Kind}.String()
	GCPIAMRole_KindAPIVersion   = GCPIAMRole_Kind + "." + CRDGroupVersion.String()
	GCPIAMRole_GroupVersionKind = CRDGroupVersion.WithKind(GCPIAMRole_Kind)
)

func init() {
	SchemeBuilder.Register(&GCPIAMRole{}, &GCPIAMRoleList{})
}
