// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type IAMRoleInitParameters struct {

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number)
	GCPRoleLaunchStage *float64 `json:"gcpRoleLaunchStage,omitempty" tf:"gcp_role_launch_stage,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUserGroups []IAMRoleOwnerUserGroupsInitParameters `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUsers []IAMRoleOwnerUsersInitParameters `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (Set of String)
	// +listType=set
	RolePermissions []*string `json:"rolePermissions,omitempty" tf:"role_permissions,omitempty"`

	// (Boolean)
	SystemManagedPolicy *bool `json:"systemManagedPolicy,omitempty" tf:"system_managed_policy,omitempty"`
}

type IAMRoleObservation struct {

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	GCPID *string `json:"gcpId,omitempty" tf:"gcp_id,omitempty"`

	// (Boolean)
	GCPManagedPolicy *bool `json:"gcpManagedPolicy,omitempty" tf:"gcp_managed_policy,omitempty"`

	// (Number)
	GCPRoleLaunchStage *float64 `json:"gcpRoleLaunchStage,omitempty" tf:"gcp_role_launch_stage,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUserGroups []IAMRoleOwnerUserGroupsObservation `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	OwnerUsers []IAMRoleOwnerUsersObservation `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (Set of String)
	// +listType=set
	RolePermissions []*string `json:"rolePermissions,omitempty" tf:"role_permissions,omitempty"`

	// (Boolean)
	SystemManagedPolicy *bool `json:"systemManagedPolicy,omitempty" tf:"system_managed_policy,omitempty"`
}

type IAMRoleOwnerUserGroupsInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type IAMRoleOwnerUserGroupsObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type IAMRoleOwnerUserGroupsParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type IAMRoleOwnerUsersInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type IAMRoleOwnerUsersObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type IAMRoleOwnerUsersParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type IAMRoleParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	GCPRoleLaunchStage *float64 `json:"gcpRoleLaunchStage,omitempty" tf:"gcp_role_launch_stage,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	// +kubebuilder:validation:Optional
	OwnerUserGroups []IAMRoleOwnerUserGroupsParameters `json:"ownerUserGroups,omitempty" tf:"owner_user_groups,omitempty"`

	// (Block Set) Must provide at least the owner_user_groups field or the owner_users field. (see below for nested schema)
	// Must provide at least the owner_user_groups field or the owner_users field.
	// +kubebuilder:validation:Optional
	OwnerUsers []IAMRoleOwnerUsersParameters `json:"ownerUsers,omitempty" tf:"owner_users,omitempty"`

	// (Set of String)
	// +kubebuilder:validation:Optional
	// +listType=set
	RolePermissions []*string `json:"rolePermissions,omitempty" tf:"role_permissions,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	SystemManagedPolicy *bool `json:"systemManagedPolicy,omitempty" tf:"system_managed_policy,omitempty"`
}

// IAMRoleSpec defines the desired state of IAMRole
type IAMRoleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IAMRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IAMRoleInitParameters `json:"initProvider,omitempty"`
}

// IAMRoleStatus defines the observed state of IAMRole.
type IAMRoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IAMRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IAMRole is the Schema for the IAMRoles API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type IAMRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.gcpRoleLaunchStage) || (has(self.initProvider) && has(self.initProvider.gcpRoleLaunchStage))",message="spec.forProvider.gcpRoleLaunchStage is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.rolePermissions) || (has(self.initProvider) && has(self.initProvider.rolePermissions))",message="spec.forProvider.rolePermissions is a required parameter"
	Spec   IAMRoleSpec   `json:"spec"`
	Status IAMRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IAMRoleList contains a list of IAMRoles
type IAMRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IAMRole `json:"items"`
}

// Repository type metadata.
var (
	IAMRole_Kind             = "IAMRole"
	IAMRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IAMRole_Kind}.String()
	IAMRole_KindAPIVersion   = IAMRole_Kind + "." + CRDGroupVersion.String()
	IAMRole_GroupVersionKind = CRDGroupVersion.WithKind(IAMRole_Kind)
)

func init() {
	SchemeBuilder.Register(&IAMRole{}, &IAMRoleList{})
}
