// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type OUPermissionMappingInitParameters struct {

	// (Number) Application role ID for the permission mapping.
	// Application role ID for the permission mapping.
	AppRoleID *float64 `json:"appRoleId,omitempty" tf:"app_role_id,omitempty"`

	// (Number) ID of the OU to manage permission mappings for.
	// ID of the OU to manage permission mappings for.
	OuID *float64 `json:"ouId,omitempty" tf:"ou_id,omitempty"`

	// (Set of Number) Set of user group IDs for the permission mapping (must be provided in numerical order).
	// Set of user group IDs for the permission mapping (must be provided in numerical order).
	// +listType=set
	UserGroupsIds []*float64 `json:"userGroupsIds,omitempty" tf:"user_groups_ids,omitempty"`

	// (Set of Number) Set of user IDs for the permission mapping (must be provided in numerical order).
	// Set of user IDs for the permission mapping (must be provided in numerical order).
	// +listType=set
	UserIds []*float64 `json:"userIds,omitempty" tf:"user_ids,omitempty"`
}

type OUPermissionMappingObservation struct {

	// (Number) Application role ID for the permission mapping.
	// Application role ID for the permission mapping.
	AppRoleID *float64 `json:"appRoleId,omitempty" tf:"app_role_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) ID of the OU to manage permission mappings for.
	// ID of the OU to manage permission mappings for.
	OuID *float64 `json:"ouId,omitempty" tf:"ou_id,omitempty"`

	// (Set of Number) Set of user group IDs for the permission mapping (must be provided in numerical order).
	// Set of user group IDs for the permission mapping (must be provided in numerical order).
	// +listType=set
	UserGroupsIds []*float64 `json:"userGroupsIds,omitempty" tf:"user_groups_ids,omitempty"`

	// (Set of Number) Set of user IDs for the permission mapping (must be provided in numerical order).
	// Set of user IDs for the permission mapping (must be provided in numerical order).
	// +listType=set
	UserIds []*float64 `json:"userIds,omitempty" tf:"user_ids,omitempty"`
}

type OUPermissionMappingParameters struct {

	// (Number) Application role ID for the permission mapping.
	// Application role ID for the permission mapping.
	// +kubebuilder:validation:Optional
	AppRoleID *float64 `json:"appRoleId,omitempty" tf:"app_role_id,omitempty"`

	// (Number) ID of the OU to manage permission mappings for.
	// ID of the OU to manage permission mappings for.
	// +kubebuilder:validation:Optional
	OuID *float64 `json:"ouId,omitempty" tf:"ou_id,omitempty"`

	// (Set of Number) Set of user group IDs for the permission mapping (must be provided in numerical order).
	// Set of user group IDs for the permission mapping (must be provided in numerical order).
	// +kubebuilder:validation:Optional
	// +listType=set
	UserGroupsIds []*float64 `json:"userGroupsIds,omitempty" tf:"user_groups_ids,omitempty"`

	// (Set of Number) Set of user IDs for the permission mapping (must be provided in numerical order).
	// Set of user IDs for the permission mapping (must be provided in numerical order).
	// +kubebuilder:validation:Optional
	// +listType=set
	UserIds []*float64 `json:"userIds,omitempty" tf:"user_ids,omitempty"`
}

// OUPermissionMappingSpec defines the desired state of OUPermissionMapping
type OUPermissionMappingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OUPermissionMappingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OUPermissionMappingInitParameters `json:"initProvider,omitempty"`
}

// OUPermissionMappingStatus defines the observed state of OUPermissionMapping.
type OUPermissionMappingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OUPermissionMappingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OUPermissionMapping is the Schema for the OUPermissionMappings API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type OUPermissionMapping struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.appRoleId) || (has(self.initProvider) && has(self.initProvider.appRoleId))",message="spec.forProvider.appRoleId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ouId) || (has(self.initProvider) && has(self.initProvider.ouId))",message="spec.forProvider.ouId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userGroupsIds) || (has(self.initProvider) && has(self.initProvider.userGroupsIds))",message="spec.forProvider.userGroupsIds is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userIds) || (has(self.initProvider) && has(self.initProvider.userIds))",message="spec.forProvider.userIds is a required parameter"
	Spec   OUPermissionMappingSpec   `json:"spec"`
	Status OUPermissionMappingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OUPermissionMappingList contains a list of OUPermissionMappings
type OUPermissionMappingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OUPermissionMapping `json:"items"`
}

// Repository type metadata.
var (
	OUPermissionMapping_Kind             = "OUPermissionMapping"
	OUPermissionMapping_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OUPermissionMapping_Kind}.String()
	OUPermissionMapping_KindAPIVersion   = OUPermissionMapping_Kind + "." + CRDGroupVersion.String()
	OUPermissionMapping_GroupVersionKind = CRDGroupVersion.WithKind(OUPermissionMapping_Kind)
)

func init() {
	SchemeBuilder.Register(&OUPermissionMapping{}, &OUPermissionMappingList{})
}
