// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type OUCloudAccessRoleAwsIAMPoliciesInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type OUCloudAccessRoleAwsIAMPoliciesObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type OUCloudAccessRoleAwsIAMPoliciesParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type OUCloudAccessRoleAzureRoleDefinitionsInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type OUCloudAccessRoleAzureRoleDefinitionsObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type OUCloudAccessRoleAzureRoleDefinitionsParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type OUCloudAccessRoleGCPIAMRolesInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type OUCloudAccessRoleGCPIAMRolesObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type OUCloudAccessRoleGCPIAMRolesParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type OUCloudAccessRoleInitParameters struct {

	// (String)
	AwsIAMPath *string `json:"awsIamPath,omitempty" tf:"aws_iam_path,omitempty"`

	// (Number)
	AwsIAMPermissionsBoundary *float64 `json:"awsIamPermissionsBoundary,omitempty" tf:"aws_iam_permissions_boundary,omitempty"`

	// (Block Set) (see below for nested schema)
	AwsIAMPolicies []OUCloudAccessRoleAwsIAMPoliciesInitParameters `json:"awsIamPolicies,omitempty" tf:"aws_iam_policies,omitempty"`

	// (String)
	AwsIAMRoleName *string `json:"awsIamRoleName,omitempty" tf:"aws_iam_role_name,omitempty"`

	// (Block Set) (see below for nested schema)
	AzureRoleDefinitions []OUCloudAccessRoleAzureRoleDefinitionsInitParameters `json:"azureRoleDefinitions,omitempty" tf:"azure_role_definitions,omitempty"`

	// (Block Set) (see below for nested schema)
	GCPIAMRoles []OUCloudAccessRoleGCPIAMRolesInitParameters `json:"gcpIamRoles,omitempty" tf:"gcp_iam_roles,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Boolean)
	LongTermAccessKeys *bool `json:"longTermAccessKeys,omitempty" tf:"long_term_access_keys,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number)
	OuID *float64 `json:"ouId,omitempty" tf:"ou_id,omitempty"`

	// (Boolean)
	ShortTermAccessKeys *bool `json:"shortTermAccessKeys,omitempty" tf:"short_term_access_keys,omitempty"`

	// (Block Set) (see below for nested schema)
	UserGroups []UserGroupsInitParameters `json:"userGroups,omitempty" tf:"user_groups,omitempty"`

	// (Block Set) (see below for nested schema)
	Users []UsersInitParameters `json:"users,omitempty" tf:"users,omitempty"`

	// (Boolean)
	WebAccess *bool `json:"webAccess,omitempty" tf:"web_access,omitempty"`
}

type OUCloudAccessRoleObservation struct {

	// (String)
	AwsIAMPath *string `json:"awsIamPath,omitempty" tf:"aws_iam_path,omitempty"`

	// (Number)
	AwsIAMPermissionsBoundary *float64 `json:"awsIamPermissionsBoundary,omitempty" tf:"aws_iam_permissions_boundary,omitempty"`

	// (Block Set) (see below for nested schema)
	AwsIAMPolicies []OUCloudAccessRoleAwsIAMPoliciesObservation `json:"awsIamPolicies,omitempty" tf:"aws_iam_policies,omitempty"`

	// (String)
	AwsIAMRoleName *string `json:"awsIamRoleName,omitempty" tf:"aws_iam_role_name,omitempty"`

	// (Block Set) (see below for nested schema)
	AzureRoleDefinitions []OUCloudAccessRoleAzureRoleDefinitionsObservation `json:"azureRoleDefinitions,omitempty" tf:"azure_role_definitions,omitempty"`

	// (Block Set) (see below for nested schema)
	GCPIAMRoles []OUCloudAccessRoleGCPIAMRolesObservation `json:"gcpIamRoles,omitempty" tf:"gcp_iam_roles,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Boolean)
	LongTermAccessKeys *bool `json:"longTermAccessKeys,omitempty" tf:"long_term_access_keys,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number)
	OuID *float64 `json:"ouId,omitempty" tf:"ou_id,omitempty"`

	// (Boolean)
	ShortTermAccessKeys *bool `json:"shortTermAccessKeys,omitempty" tf:"short_term_access_keys,omitempty"`

	// (Block Set) (see below for nested schema)
	UserGroups []UserGroupsObservation `json:"userGroups,omitempty" tf:"user_groups,omitempty"`

	// (Block Set) (see below for nested schema)
	Users []UsersObservation `json:"users,omitempty" tf:"users,omitempty"`

	// (Boolean)
	WebAccess *bool `json:"webAccess,omitempty" tf:"web_access,omitempty"`
}

type OUCloudAccessRoleParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	AwsIAMPath *string `json:"awsIamPath,omitempty" tf:"aws_iam_path,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	AwsIAMPermissionsBoundary *float64 `json:"awsIamPermissionsBoundary,omitempty" tf:"aws_iam_permissions_boundary,omitempty"`

	// (Block Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	AwsIAMPolicies []OUCloudAccessRoleAwsIAMPoliciesParameters `json:"awsIamPolicies,omitempty" tf:"aws_iam_policies,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	AwsIAMRoleName *string `json:"awsIamRoleName,omitempty" tf:"aws_iam_role_name,omitempty"`

	// (Block Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	AzureRoleDefinitions []OUCloudAccessRoleAzureRoleDefinitionsParameters `json:"azureRoleDefinitions,omitempty" tf:"azure_role_definitions,omitempty"`

	// (Block Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	GCPIAMRoles []OUCloudAccessRoleGCPIAMRolesParameters `json:"gcpIamRoles,omitempty" tf:"gcp_iam_roles,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	LongTermAccessKeys *bool `json:"longTermAccessKeys,omitempty" tf:"long_term_access_keys,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	OuID *float64 `json:"ouId,omitempty" tf:"ou_id,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	ShortTermAccessKeys *bool `json:"shortTermAccessKeys,omitempty" tf:"short_term_access_keys,omitempty"`

	// (Block Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	UserGroups []UserGroupsParameters `json:"userGroups,omitempty" tf:"user_groups,omitempty"`

	// (Block Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Users []UsersParameters `json:"users,omitempty" tf:"users,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	WebAccess *bool `json:"webAccess,omitempty" tf:"web_access,omitempty"`
}

type UserGroupsInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type UserGroupsObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type UserGroupsParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type UsersInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type UsersObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type UsersParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

// OUCloudAccessRoleSpec defines the desired state of OUCloudAccessRole
type OUCloudAccessRoleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OUCloudAccessRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OUCloudAccessRoleInitParameters `json:"initProvider,omitempty"`
}

// OUCloudAccessRoleStatus defines the observed state of OUCloudAccessRole.
type OUCloudAccessRoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OUCloudAccessRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OUCloudAccessRole is the Schema for the OUCloudAccessRoles API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type OUCloudAccessRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ouId) || (has(self.initProvider) && has(self.initProvider.ouId))",message="spec.forProvider.ouId is a required parameter"
	Spec   OUCloudAccessRoleSpec   `json:"spec"`
	Status OUCloudAccessRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OUCloudAccessRoleList contains a list of OUCloudAccessRoles
type OUCloudAccessRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OUCloudAccessRole `json:"items"`
}

// Repository type metadata.
var (
	OUCloudAccessRole_Kind             = "OUCloudAccessRole"
	OUCloudAccessRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OUCloudAccessRole_Kind}.String()
	OUCloudAccessRole_KindAPIVersion   = OUCloudAccessRole_Kind + "." + CRDGroupVersion.String()
	OUCloudAccessRole_GroupVersionKind = CRDGroupVersion.WithKind(OUCloudAccessRole_Kind)
)

func init() {
	SchemeBuilder.Register(&OUCloudAccessRole{}, &OUCloudAccessRoleList{})
}
