// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ProjectEnforcementInitParameters struct {

	// (String) Type of the amount. Valid values are 'custom', 'last_month'.
	// Type of the amount. Valid values are 'custom', 'last_month'.
	AmountType *string `json:"amountType,omitempty" tf:"amount_type,omitempty"`

	// (Number) Defines a Cloud Rule ID associated with the enforcement.
	// Defines a Cloud Rule ID associated with the enforcement.
	CloudRuleID *float64 `json:"cloudRuleId,omitempty" tf:"cloud_rule_id,omitempty"`

	// provided description of the enforcement.
	// Optional, user-provided description of the enforcement.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Flag that specifies if the enforcement is enabled.
	// Flag that specifies if the enforcement is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Frequency at which notifications are sent for this enforcement.
	// Frequency at which notifications are sent for this enforcement.
	NotificationFrequency *string `json:"notificationFrequency,omitempty" tf:"notification_frequency,omitempty"`

	// (Boolean) Flag that specifies if enforcement will place project in an overburn state when triggered.
	// Flag that specifies if enforcement will place project in an overburn state when triggered.
	Overburn *bool `json:"overburn,omitempty" tf:"overburn,omitempty"`

	// (Number) ID of the project under enforcement.
	// ID of the project under enforcement.
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Number) ID of the service related to the enforcement.
	// ID of the service related to the enforcement.
	ServiceID *float64 `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// (String) Type of spend option. Valid values are 'spend', 'remaining'.
	// Type of spend option. Valid values are 'spend', 'remaining'.
	SpendOption *string `json:"spendOption,omitempty" tf:"spend_option,omitempty"`

	// (Number) Threshold value. Either a dollar amount or a percentage, depending on the threshold type.
	// Threshold value. Either a dollar amount or a percentage, depending on the threshold type.
	Threshold *float64 `json:"threshold,omitempty" tf:"threshold,omitempty"`

	// (String) Type of the threshold value. Valid values are 'dollar', 'percent'.
	// Type of the threshold value. Valid values are 'dollar', 'percent'.
	ThresholdType *string `json:"thresholdType,omitempty" tf:"threshold_type,omitempty"`

	// (String) Timeframe of the enforcement. Valid values are 'lifetime', 'month', 'year', 'funding_source'.
	// Timeframe of the enforcement. Valid values are 'lifetime', 'month', 'year', 'funding_source'.
	Timeframe *string `json:"timeframe,omitempty" tf:"timeframe,omitempty"`

	// (List of Number) List of user group IDs that will receive notifications from the enforcement.
	// List of user group IDs that will receive notifications from the enforcement.
	UserGroupIds []*float64 `json:"userGroupIds,omitempty" tf:"user_group_ids,omitempty"`

	// (List of Number) List of user IDs that will receive notifications from the enforcement.
	// List of user IDs that will receive notifications from the enforcement.
	UserIds []*float64 `json:"userIds,omitempty" tf:"user_ids,omitempty"`
}

type ProjectEnforcementObservation struct {

	// (String) Type of the amount. Valid values are 'custom', 'last_month'.
	// Type of the amount. Valid values are 'custom', 'last_month'.
	AmountType *string `json:"amountType,omitempty" tf:"amount_type,omitempty"`

	// (Number) Defines a Cloud Rule ID associated with the enforcement.
	// Defines a Cloud Rule ID associated with the enforcement.
	CloudRuleID *float64 `json:"cloudRuleId,omitempty" tf:"cloud_rule_id,omitempty"`

	// provided description of the enforcement.
	// Optional, user-provided description of the enforcement.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Flag that specifies if the enforcement is enabled.
	// Flag that specifies if the enforcement is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Frequency at which notifications are sent for this enforcement.
	// Frequency at which notifications are sent for this enforcement.
	NotificationFrequency *string `json:"notificationFrequency,omitempty" tf:"notification_frequency,omitempty"`

	// (Boolean) Flag that specifies if enforcement will place project in an overburn state when triggered.
	// Flag that specifies if enforcement will place project in an overburn state when triggered.
	Overburn *bool `json:"overburn,omitempty" tf:"overburn,omitempty"`

	// (Number) ID of the project under enforcement.
	// ID of the project under enforcement.
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Number) ID of the service related to the enforcement.
	// ID of the service related to the enforcement.
	ServiceID *float64 `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// (String) Type of spend option. Valid values are 'spend', 'remaining'.
	// Type of spend option. Valid values are 'spend', 'remaining'.
	SpendOption *string `json:"spendOption,omitempty" tf:"spend_option,omitempty"`

	// (Number) Threshold value. Either a dollar amount or a percentage, depending on the threshold type.
	// Threshold value. Either a dollar amount or a percentage, depending on the threshold type.
	Threshold *float64 `json:"threshold,omitempty" tf:"threshold,omitempty"`

	// (String) Type of the threshold value. Valid values are 'dollar', 'percent'.
	// Type of the threshold value. Valid values are 'dollar', 'percent'.
	ThresholdType *string `json:"thresholdType,omitempty" tf:"threshold_type,omitempty"`

	// (String) Timeframe of the enforcement. Valid values are 'lifetime', 'month', 'year', 'funding_source'.
	// Timeframe of the enforcement. Valid values are 'lifetime', 'month', 'year', 'funding_source'.
	Timeframe *string `json:"timeframe,omitempty" tf:"timeframe,omitempty"`

	// (Boolean) Flag that specifies if the enforcement is currently triggered.
	// Flag that specifies if the enforcement is currently triggered.
	Triggered *bool `json:"triggered,omitempty" tf:"triggered,omitempty"`

	// (List of Number) List of user group IDs that will receive notifications from the enforcement.
	// List of user group IDs that will receive notifications from the enforcement.
	UserGroupIds []*float64 `json:"userGroupIds,omitempty" tf:"user_group_ids,omitempty"`

	// (List of Number) List of user IDs that will receive notifications from the enforcement.
	// List of user IDs that will receive notifications from the enforcement.
	UserIds []*float64 `json:"userIds,omitempty" tf:"user_ids,omitempty"`
}

type ProjectEnforcementParameters struct {

	// (String) Type of the amount. Valid values are 'custom', 'last_month'.
	// Type of the amount. Valid values are 'custom', 'last_month'.
	// +kubebuilder:validation:Optional
	AmountType *string `json:"amountType,omitempty" tf:"amount_type,omitempty"`

	// (Number) Defines a Cloud Rule ID associated with the enforcement.
	// Defines a Cloud Rule ID associated with the enforcement.
	// +kubebuilder:validation:Optional
	CloudRuleID *float64 `json:"cloudRuleId,omitempty" tf:"cloud_rule_id,omitempty"`

	// provided description of the enforcement.
	// Optional, user-provided description of the enforcement.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Flag that specifies if the enforcement is enabled.
	// Flag that specifies if the enforcement is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Frequency at which notifications are sent for this enforcement.
	// Frequency at which notifications are sent for this enforcement.
	// +kubebuilder:validation:Optional
	NotificationFrequency *string `json:"notificationFrequency,omitempty" tf:"notification_frequency,omitempty"`

	// (Boolean) Flag that specifies if enforcement will place project in an overburn state when triggered.
	// Flag that specifies if enforcement will place project in an overburn state when triggered.
	// +kubebuilder:validation:Optional
	Overburn *bool `json:"overburn,omitempty" tf:"overburn,omitempty"`

	// (Number) ID of the project under enforcement.
	// ID of the project under enforcement.
	// +kubebuilder:validation:Optional
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Number) ID of the service related to the enforcement.
	// ID of the service related to the enforcement.
	// +kubebuilder:validation:Optional
	ServiceID *float64 `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// (String) Type of spend option. Valid values are 'spend', 'remaining'.
	// Type of spend option. Valid values are 'spend', 'remaining'.
	// +kubebuilder:validation:Optional
	SpendOption *string `json:"spendOption,omitempty" tf:"spend_option,omitempty"`

	// (Number) Threshold value. Either a dollar amount or a percentage, depending on the threshold type.
	// Threshold value. Either a dollar amount or a percentage, depending on the threshold type.
	// +kubebuilder:validation:Optional
	Threshold *float64 `json:"threshold,omitempty" tf:"threshold,omitempty"`

	// (String) Type of the threshold value. Valid values are 'dollar', 'percent'.
	// Type of the threshold value. Valid values are 'dollar', 'percent'.
	// +kubebuilder:validation:Optional
	ThresholdType *string `json:"thresholdType,omitempty" tf:"threshold_type,omitempty"`

	// (String) Timeframe of the enforcement. Valid values are 'lifetime', 'month', 'year', 'funding_source'.
	// Timeframe of the enforcement. Valid values are 'lifetime', 'month', 'year', 'funding_source'.
	// +kubebuilder:validation:Optional
	Timeframe *string `json:"timeframe,omitempty" tf:"timeframe,omitempty"`

	// (List of Number) List of user group IDs that will receive notifications from the enforcement.
	// List of user group IDs that will receive notifications from the enforcement.
	// +kubebuilder:validation:Optional
	UserGroupIds []*float64 `json:"userGroupIds,omitempty" tf:"user_group_ids,omitempty"`

	// (List of Number) List of user IDs that will receive notifications from the enforcement.
	// List of user IDs that will receive notifications from the enforcement.
	// +kubebuilder:validation:Optional
	UserIds []*float64 `json:"userIds,omitempty" tf:"user_ids,omitempty"`
}

// ProjectEnforcementSpec defines the desired state of ProjectEnforcement
type ProjectEnforcementSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProjectEnforcementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectEnforcementInitParameters `json:"initProvider,omitempty"`
}

// ProjectEnforcementStatus defines the observed state of ProjectEnforcement.
type ProjectEnforcementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectEnforcementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectEnforcement is the Schema for the ProjectEnforcements API. Manages enforcement rules for projects to control service usage based on various criteria likespend limits and timeframe restrictions. . This resource allows for creating, reading, updating, and deleting project-specific enforcement settings.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type ProjectEnforcement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.threshold) || (has(self.initProvider) && has(self.initProvider.threshold))",message="spec.forProvider.threshold is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.timeframe) || (has(self.initProvider) && has(self.initProvider.timeframe))",message="spec.forProvider.timeframe is a required parameter"
	Spec   ProjectEnforcementSpec   `json:"spec"`
	Status ProjectEnforcementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectEnforcementList contains a list of ProjectEnforcements
type ProjectEnforcementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectEnforcement `json:"items"`
}

// Repository type metadata.
var (
	ProjectEnforcement_Kind             = "ProjectEnforcement"
	ProjectEnforcement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectEnforcement_Kind}.String()
	ProjectEnforcement_KindAPIVersion   = ProjectEnforcement_Kind + "." + CRDGroupVersion.String()
	ProjectEnforcement_GroupVersionKind = CRDGroupVersion.WithKind(ProjectEnforcement_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectEnforcement{}, &ProjectEnforcementList{})
}
