// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ProjectPermissionMappingInitParameters struct {

	// Application role ID for the permission mapping.
	AppRoleID *float64 `json:"appRoleId,omitempty" tf:"app_role_id,omitempty"`

	// ID of the project to manage permission mappings for.
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Set of user group IDs for the permission mapping (must be provided in numerical order).
	// +listType=set
	UserGroupsIds []*float64 `json:"userGroupsIds,omitempty" tf:"user_groups_ids,omitempty"`

	// Set of user IDs for the permission mapping (must be provided in numerical order).
	// +listType=set
	UserIds []*float64 `json:"userIds,omitempty" tf:"user_ids,omitempty"`
}

type ProjectPermissionMappingObservation struct {

	// Application role ID for the permission mapping.
	AppRoleID *float64 `json:"appRoleId,omitempty" tf:"app_role_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// ID of the project to manage permission mappings for.
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Set of user group IDs for the permission mapping (must be provided in numerical order).
	// +listType=set
	UserGroupsIds []*float64 `json:"userGroupsIds,omitempty" tf:"user_groups_ids,omitempty"`

	// Set of user IDs for the permission mapping (must be provided in numerical order).
	// +listType=set
	UserIds []*float64 `json:"userIds,omitempty" tf:"user_ids,omitempty"`
}

type ProjectPermissionMappingParameters struct {

	// Application role ID for the permission mapping.
	// +kubebuilder:validation:Optional
	AppRoleID *float64 `json:"appRoleId,omitempty" tf:"app_role_id,omitempty"`

	// ID of the project to manage permission mappings for.
	// +kubebuilder:validation:Optional
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Set of user group IDs for the permission mapping (must be provided in numerical order).
	// +kubebuilder:validation:Optional
	// +listType=set
	UserGroupsIds []*float64 `json:"userGroupsIds,omitempty" tf:"user_groups_ids,omitempty"`

	// Set of user IDs for the permission mapping (must be provided in numerical order).
	// +kubebuilder:validation:Optional
	// +listType=set
	UserIds []*float64 `json:"userIds,omitempty" tf:"user_ids,omitempty"`
}

// ProjectPermissionMappingSpec defines the desired state of ProjectPermissionMapping
type ProjectPermissionMappingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProjectPermissionMappingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectPermissionMappingInitParameters `json:"initProvider,omitempty"`
}

// ProjectPermissionMappingStatus defines the observed state of ProjectPermissionMapping.
type ProjectPermissionMappingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectPermissionMappingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectPermissionMapping is the Schema for the ProjectPermissionMappings API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type ProjectPermissionMapping struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.appRoleId) || (has(self.initProvider) && has(self.initProvider.appRoleId))",message="spec.forProvider.appRoleId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userGroupsIds) || (has(self.initProvider) && has(self.initProvider.userGroupsIds))",message="spec.forProvider.userGroupsIds is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userIds) || (has(self.initProvider) && has(self.initProvider.userIds))",message="spec.forProvider.userIds is a required parameter"
	Spec   ProjectPermissionMappingSpec   `json:"spec"`
	Status ProjectPermissionMappingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectPermissionMappingList contains a list of ProjectPermissionMappings
type ProjectPermissionMappingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectPermissionMapping `json:"items"`
}

// Repository type metadata.
var (
	ProjectPermissionMapping_Kind             = "ProjectPermissionMapping"
	ProjectPermissionMapping_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectPermissionMapping_Kind}.String()
	ProjectPermissionMapping_KindAPIVersion   = ProjectPermissionMapping_Kind + "." + CRDGroupVersion.String()
	ProjectPermissionMapping_GroupVersionKind = CRDGroupVersion.WithKind(ProjectPermissionMapping_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectPermissionMapping{}, &ProjectPermissionMappingList{})
}
