// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AccountsInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type AccountsObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type AccountsParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ProjectCloudAccessRoleAwsIAMPoliciesInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ProjectCloudAccessRoleAwsIAMPoliciesObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ProjectCloudAccessRoleAwsIAMPoliciesParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ProjectCloudAccessRoleAzureRoleDefinitionsInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ProjectCloudAccessRoleAzureRoleDefinitionsObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ProjectCloudAccessRoleAzureRoleDefinitionsParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ProjectCloudAccessRoleGCPIAMRolesInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ProjectCloudAccessRoleGCPIAMRolesObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ProjectCloudAccessRoleGCPIAMRolesParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ProjectCloudAccessRoleInitParameters struct {

	// (Block Set) This field will be ignored if 'apply_to_all_accounts' is set to: true. (see below for nested schema)
	// This field will be ignored if 'apply_to_all_accounts' is set to: true.
	Accounts []AccountsInitParameters `json:"accounts,omitempty" tf:"accounts,omitempty"`

	// (Boolean)
	ApplyToAllAccounts *bool `json:"applyToAllAccounts,omitempty" tf:"apply_to_all_accounts,omitempty"`

	// (String)
	AwsIAMPath *string `json:"awsIamPath,omitempty" tf:"aws_iam_path,omitempty"`

	// (Number)
	AwsIAMPermissionsBoundary *float64 `json:"awsIamPermissionsBoundary,omitempty" tf:"aws_iam_permissions_boundary,omitempty"`

	// (Block Set) (see below for nested schema)
	AwsIAMPolicies []ProjectCloudAccessRoleAwsIAMPoliciesInitParameters `json:"awsIamPolicies,omitempty" tf:"aws_iam_policies,omitempty"`

	// (String)
	AwsIAMRoleName *string `json:"awsIamRoleName,omitempty" tf:"aws_iam_role_name,omitempty"`

	// (Block Set) (see below for nested schema)
	AzureRoleDefinitions []ProjectCloudAccessRoleAzureRoleDefinitionsInitParameters `json:"azureRoleDefinitions,omitempty" tf:"azure_role_definitions,omitempty"`

	// (Boolean)
	FutureAccounts *bool `json:"futureAccounts,omitempty" tf:"future_accounts,omitempty"`

	// (Block Set) (see below for nested schema)
	GCPIAMRoles []ProjectCloudAccessRoleGCPIAMRolesInitParameters `json:"gcpIamRoles,omitempty" tf:"gcp_iam_roles,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Boolean)
	LongTermAccessKeys *bool `json:"longTermAccessKeys,omitempty" tf:"long_term_access_keys,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number)
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Boolean)
	ShortTermAccessKeys *bool `json:"shortTermAccessKeys,omitempty" tf:"short_term_access_keys,omitempty"`

	// (Block Set) (see below for nested schema)
	UserGroups []ProjectCloudAccessRoleUserGroupsInitParameters `json:"userGroups,omitempty" tf:"user_groups,omitempty"`

	// (Block Set) (see below for nested schema)
	Users []ProjectCloudAccessRoleUsersInitParameters `json:"users,omitempty" tf:"users,omitempty"`

	// (Boolean)
	WebAccess *bool `json:"webAccess,omitempty" tf:"web_access,omitempty"`
}

type ProjectCloudAccessRoleObservation struct {

	// (Block Set) This field will be ignored if 'apply_to_all_accounts' is set to: true. (see below for nested schema)
	// This field will be ignored if 'apply_to_all_accounts' is set to: true.
	Accounts []AccountsObservation `json:"accounts,omitempty" tf:"accounts,omitempty"`

	// (Boolean)
	ApplyToAllAccounts *bool `json:"applyToAllAccounts,omitempty" tf:"apply_to_all_accounts,omitempty"`

	// (String)
	AwsIAMPath *string `json:"awsIamPath,omitempty" tf:"aws_iam_path,omitempty"`

	// (Number)
	AwsIAMPermissionsBoundary *float64 `json:"awsIamPermissionsBoundary,omitempty" tf:"aws_iam_permissions_boundary,omitempty"`

	// (Block Set) (see below for nested schema)
	AwsIAMPolicies []ProjectCloudAccessRoleAwsIAMPoliciesObservation `json:"awsIamPolicies,omitempty" tf:"aws_iam_policies,omitempty"`

	// (String)
	AwsIAMRoleName *string `json:"awsIamRoleName,omitempty" tf:"aws_iam_role_name,omitempty"`

	// (Block Set) (see below for nested schema)
	AzureRoleDefinitions []ProjectCloudAccessRoleAzureRoleDefinitionsObservation `json:"azureRoleDefinitions,omitempty" tf:"azure_role_definitions,omitempty"`

	// (Boolean)
	FutureAccounts *bool `json:"futureAccounts,omitempty" tf:"future_accounts,omitempty"`

	// (Block Set) (see below for nested schema)
	GCPIAMRoles []ProjectCloudAccessRoleGCPIAMRolesObservation `json:"gcpIamRoles,omitempty" tf:"gcp_iam_roles,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Boolean)
	LongTermAccessKeys *bool `json:"longTermAccessKeys,omitempty" tf:"long_term_access_keys,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number)
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Boolean)
	ShortTermAccessKeys *bool `json:"shortTermAccessKeys,omitempty" tf:"short_term_access_keys,omitempty"`

	// (Block Set) (see below for nested schema)
	UserGroups []ProjectCloudAccessRoleUserGroupsObservation `json:"userGroups,omitempty" tf:"user_groups,omitempty"`

	// (Block Set) (see below for nested schema)
	Users []ProjectCloudAccessRoleUsersObservation `json:"users,omitempty" tf:"users,omitempty"`

	// (Boolean)
	WebAccess *bool `json:"webAccess,omitempty" tf:"web_access,omitempty"`
}

type ProjectCloudAccessRoleParameters struct {

	// (Block Set) This field will be ignored if 'apply_to_all_accounts' is set to: true. (see below for nested schema)
	// This field will be ignored if 'apply_to_all_accounts' is set to: true.
	// +kubebuilder:validation:Optional
	Accounts []AccountsParameters `json:"accounts,omitempty" tf:"accounts,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	ApplyToAllAccounts *bool `json:"applyToAllAccounts,omitempty" tf:"apply_to_all_accounts,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	AwsIAMPath *string `json:"awsIamPath,omitempty" tf:"aws_iam_path,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	AwsIAMPermissionsBoundary *float64 `json:"awsIamPermissionsBoundary,omitempty" tf:"aws_iam_permissions_boundary,omitempty"`

	// (Block Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	AwsIAMPolicies []ProjectCloudAccessRoleAwsIAMPoliciesParameters `json:"awsIamPolicies,omitempty" tf:"aws_iam_policies,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	AwsIAMRoleName *string `json:"awsIamRoleName,omitempty" tf:"aws_iam_role_name,omitempty"`

	// (Block Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	AzureRoleDefinitions []ProjectCloudAccessRoleAzureRoleDefinitionsParameters `json:"azureRoleDefinitions,omitempty" tf:"azure_role_definitions,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	FutureAccounts *bool `json:"futureAccounts,omitempty" tf:"future_accounts,omitempty"`

	// (Block Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	GCPIAMRoles []ProjectCloudAccessRoleGCPIAMRolesParameters `json:"gcpIamRoles,omitempty" tf:"gcp_iam_roles,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	LongTermAccessKeys *bool `json:"longTermAccessKeys,omitempty" tf:"long_term_access_keys,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	ShortTermAccessKeys *bool `json:"shortTermAccessKeys,omitempty" tf:"short_term_access_keys,omitempty"`

	// (Block Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	UserGroups []ProjectCloudAccessRoleUserGroupsParameters `json:"userGroups,omitempty" tf:"user_groups,omitempty"`

	// (Block Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Users []ProjectCloudAccessRoleUsersParameters `json:"users,omitempty" tf:"users,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	WebAccess *bool `json:"webAccess,omitempty" tf:"web_access,omitempty"`
}

type ProjectCloudAccessRoleUserGroupsInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ProjectCloudAccessRoleUserGroupsObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ProjectCloudAccessRoleUserGroupsParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ProjectCloudAccessRoleUsersInitParameters struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ProjectCloudAccessRoleUsersObservation struct {

	// (String) The ID of this resource.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type ProjectCloudAccessRoleUsersParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

// ProjectCloudAccessRoleSpec defines the desired state of ProjectCloudAccessRole
type ProjectCloudAccessRoleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProjectCloudAccessRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectCloudAccessRoleInitParameters `json:"initProvider,omitempty"`
}

// ProjectCloudAccessRoleStatus defines the observed state of ProjectCloudAccessRole.
type ProjectCloudAccessRoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectCloudAccessRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectCloudAccessRole is the Schema for the ProjectCloudAccessRoles API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type ProjectCloudAccessRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.awsIamRoleName) || (has(self.initProvider) && has(self.initProvider.awsIamRoleName))",message="spec.forProvider.awsIamRoleName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	Spec   ProjectCloudAccessRoleSpec   `json:"spec"`
	Status ProjectCloudAccessRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectCloudAccessRoleList contains a list of ProjectCloudAccessRoles
type ProjectCloudAccessRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectCloudAccessRole `json:"items"`
}

// Repository type metadata.
var (
	ProjectCloudAccessRole_Kind             = "ProjectCloudAccessRole"
	ProjectCloudAccessRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectCloudAccessRole_Kind}.String()
	ProjectCloudAccessRole_KindAPIVersion   = ProjectCloudAccessRole_Kind + "." + CRDGroupVersion.String()
	ProjectCloudAccessRole_GroupVersionKind = CRDGroupVersion.WithKind(ProjectCloudAccessRole_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectCloudAccessRole{}, &ProjectCloudAccessRoleList{})
}
