// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AppConfigInitParameters struct {

	// (Boolean) Indicates whether all users can see the names of OU's in the organization chart.
	// Indicates whether all users can see the names of OU's in the organization chart.
	AllUsersSeeOuNames *bool `json:"allUsersSeeOuNames,omitempty" tf:"all_users_see_ou_names,omitempty"`

	// (Boolean) Indicates if allocation mode is enabled in the application.
	// Indicates if allocation mode is enabled in the application.
	AllocationMode *bool `json:"allocationMode,omitempty" tf:"allocation_mode,omitempty"`

	// (Boolean) Indicates whether custom permission schemes are allowed or not.
	// Indicates whether custom permission schemes are allowed or not.
	AllowCustomPermissionSchemes *bool `json:"allowCustomPermissionSchemes,omitempty" tf:"allow_custom_permission_schemes,omitempty"`

	// (Boolean) Indicates if App API Key creation is enabled.
	// Indicates if App API Key creation is enabled.
	AppAPIKeyCreationEnabled *bool `json:"appApiKeyCreationEnabled,omitempty" tf:"app_api_key_creation_enabled,omitempty"`

	// (Number) Indicates the lifespan of App API Keys in days.
	// Indicates the lifespan of App API Keys in days.
	AppAPIKeyLifespan *float64 `json:"appApiKeyLifespan,omitempty" tf:"app_api_key_lifespan,omitempty"`

	// (Number) Indicates the max amount of App API Keys per user.
	// Indicates the max amount of App API Keys per user.
	AppAPIKeyLimit *float64 `json:"appApiKeyLimit,omitempty" tf:"app_api_key_limit,omitempty"`

	// (Boolean) Indicates whether AWS access keys creation is enabled.
	// Indicates whether AWS access keys creation is enabled.
	AwsAccessKeyCreationEnabled *bool `json:"awsAccessKeyCreationEnabled,omitempty" tf:"aws_access_key_creation_enabled,omitempty"`

	// (Boolean) Indicates if budget mode is enabled in the application.
	// Indicates if budget mode is enabled in the application.
	BudgetMode *bool `json:"budgetMode,omitempty" tf:"budget_mode,omitempty"`

	// (Boolean) Indicates if cloud rules are restricted to User Group ownership only. Setting this to true will remove all users from cloud rules. This cannot be undone.
	// Indicates if cloud rules are restricted to User Group ownership only. Setting this to true will remove all users from cloud rules. This cannot be undone.
	CloudRuleGroupOwnershipOnly *bool `json:"cloudRuleGroupOwnershipOnly,omitempty" tf:"cloud_rule_group_ownership_only,omitempty"`

	// app.
	// Indicates whether resource termination is allowed in-app.
	CostSavingsAllowTerminate *bool `json:"costSavingsAllowTerminate,omitempty" tf:"cost_savings_allow_terminate,omitempty"`

	// (Boolean) Indicates whether Cost Savings is enabled or not.
	// Indicates whether Cost Savings is enabled or not.
	CostSavingsEnabled *bool `json:"costSavingsEnabled,omitempty" tf:"cost_savings_enabled,omitempty"`

	// (Number) Post token life (hours) for Cloud Custodian webhook actions to execute.
	// Post token life (hours) for Cloud Custodian webhook actions to execute.
	CostSavingsPostTokenLifeHours *float64 `json:"costSavingsPostTokenLifeHours,omitempty" tf:"cost_savings_post_token_life_hours,omitempty"`

	// (String) Defines the default organization chart view.
	// Defines the default organization chart view.
	DefaultOrgChartView *string `json:"defaultOrgChartView,omitempty" tf:"default_org_chart_view,omitempty"`

	// (Boolean) Indicates whether spend plans or budgets must be created on all projects.
	// Indicates whether spend plans or budgets must be created on all projects.
	EnforceFunding *bool `json:"enforceFunding,omitempty" tf:"enforce_funding,omitempty"`

	// (Boolean) Indicates whether every project should have a funding source.
	// Indicates whether every project should have a funding source.
	EnforceFundingSources *bool `json:"enforceFundingSources,omitempty" tf:"enforce_funding_sources,omitempty"`

	// (Boolean) Indicates whether event driven is enabled or not.
	// Indicates whether event driven is enabled or not.
	EventDrivenEnabled *bool `json:"eventDrivenEnabled,omitempty" tf:"event_driven_enabled,omitempty"`

	// (Boolean) Indicates whether forecasting is enabled or not.
	// Indicates whether forecasting is enabled or not.
	ForecastingEnabled *bool `json:"forecastingEnabled,omitempty" tf:"forecasting_enabled,omitempty"`

	// (Boolean) Indicates whether, when new groups are created via IDMS, the group will be set as a viewer by default.
	// Indicates whether, when new groups are created via IDMS, the group will be set as a viewer by default.
	IdmsGroupsAsViewersDefault *bool `json:"idmsGroupsAsViewersDefault,omitempty" tf:"idms_groups_as_viewers_default,omitempty"`

	// (Boolean) Indicates whether reserved instances are enabled or not.
	// Indicates whether reserved instances are enabled or not.
	ReservedInstancesEnabled *bool `json:"reservedInstancesEnabled,omitempty" tf:"reserved_instances_enabled,omitempty"`

	// (Boolean) Indicates whether resource inventory is enabled or not.
	// Indicates whether resource inventory is enabled or not.
	ResourceInventoryEnabled *bool `json:"resourceInventoryEnabled,omitempty" tf:"resource_inventory_enabled,omitempty"`

	// (Boolean) Indicates whether SAML debugging is enabled or not.
	// Indicates whether SAML debugging is enabled or not.
	SAMLDebug *bool `json:"samlDebug,omitempty" tf:"saml_debug,omitempty"`

	// (Boolean) Indicates whether SMTP is enabled or not.
	// Indicates whether SMTP is enabled or not.
	SMTPEnabled *bool `json:"smtpEnabled,omitempty" tf:"smtp_enabled,omitempty"`

	// (String) The SMTP from address.
	// The SMTP from address.
	SMTPFrom *string `json:"smtpFrom,omitempty" tf:"smtp_from,omitempty"`

	// (String) The SMTP host.
	// The SMTP host.
	SMTPHost *string `json:"smtpHost,omitempty" tf:"smtp_host,omitempty"`

	// (String, Sensitive) The SMTP password.
	// The SMTP password.
	SMTPPasswordSecretRef *v1.LocalSecretKeySelector `json:"smtpPasswordSecretRef,omitempty" tf:"-"`

	// (Number) The SMTP port.
	// The SMTP port.
	SMTPPort *float64 `json:"smtpPort,omitempty" tf:"smtp_port,omitempty"`

	// (Boolean) Indicates if the app should skip SMTP verification.
	// Indicates if the app should skip SMTP verification.
	SMTPSkipVerify *bool `json:"smtpSkipVerify,omitempty" tf:"smtp_skip_verify,omitempty"`

	// (String) The SMTP username.
	// The SMTP username.
	SMTPUsername *string `json:"smtpUsername,omitempty" tf:"smtp_username,omitempty"`

	// (List of String) The list of supported AWS regions.
	// The list of supported AWS regions.
	SupportedAwsRegions []*string `json:"supportedAwsRegions,omitempty" tf:"supported_aws_regions,omitempty"`
}

type AppConfigObservation struct {

	// (Boolean) Indicates whether all users can see the names of OU's in the organization chart.
	// Indicates whether all users can see the names of OU's in the organization chart.
	AllUsersSeeOuNames *bool `json:"allUsersSeeOuNames,omitempty" tf:"all_users_see_ou_names,omitempty"`

	// (Boolean) Indicates if allocation mode is enabled in the application.
	// Indicates if allocation mode is enabled in the application.
	AllocationMode *bool `json:"allocationMode,omitempty" tf:"allocation_mode,omitempty"`

	// (Boolean) Indicates whether custom permission schemes are allowed or not.
	// Indicates whether custom permission schemes are allowed or not.
	AllowCustomPermissionSchemes *bool `json:"allowCustomPermissionSchemes,omitempty" tf:"allow_custom_permission_schemes,omitempty"`

	// (Boolean) Indicates if App API Key creation is enabled.
	// Indicates if App API Key creation is enabled.
	AppAPIKeyCreationEnabled *bool `json:"appApiKeyCreationEnabled,omitempty" tf:"app_api_key_creation_enabled,omitempty"`

	// (Number) Indicates the lifespan of App API Keys in days.
	// Indicates the lifespan of App API Keys in days.
	AppAPIKeyLifespan *float64 `json:"appApiKeyLifespan,omitempty" tf:"app_api_key_lifespan,omitempty"`

	// (Number) Indicates the max amount of App API Keys per user.
	// Indicates the max amount of App API Keys per user.
	AppAPIKeyLimit *float64 `json:"appApiKeyLimit,omitempty" tf:"app_api_key_limit,omitempty"`

	// (Boolean) Indicates whether AWS access keys creation is enabled.
	// Indicates whether AWS access keys creation is enabled.
	AwsAccessKeyCreationEnabled *bool `json:"awsAccessKeyCreationEnabled,omitempty" tf:"aws_access_key_creation_enabled,omitempty"`

	// (Boolean) Indicates if budget mode is enabled in the application.
	// Indicates if budget mode is enabled in the application.
	BudgetMode *bool `json:"budgetMode,omitempty" tf:"budget_mode,omitempty"`

	// (Boolean) Indicates if cloud rules are restricted to User Group ownership only. Setting this to true will remove all users from cloud rules. This cannot be undone.
	// Indicates if cloud rules are restricted to User Group ownership only. Setting this to true will remove all users from cloud rules. This cannot be undone.
	CloudRuleGroupOwnershipOnly *bool `json:"cloudRuleGroupOwnershipOnly,omitempty" tf:"cloud_rule_group_ownership_only,omitempty"`

	// app.
	// Indicates whether resource termination is allowed in-app.
	CostSavingsAllowTerminate *bool `json:"costSavingsAllowTerminate,omitempty" tf:"cost_savings_allow_terminate,omitempty"`

	// (Boolean) Indicates whether Cost Savings is enabled or not.
	// Indicates whether Cost Savings is enabled or not.
	CostSavingsEnabled *bool `json:"costSavingsEnabled,omitempty" tf:"cost_savings_enabled,omitempty"`

	// (Number) Post token life (hours) for Cloud Custodian webhook actions to execute.
	// Post token life (hours) for Cloud Custodian webhook actions to execute.
	CostSavingsPostTokenLifeHours *float64 `json:"costSavingsPostTokenLifeHours,omitempty" tf:"cost_savings_post_token_life_hours,omitempty"`

	// (String) Defines the default organization chart view.
	// Defines the default organization chart view.
	DefaultOrgChartView *string `json:"defaultOrgChartView,omitempty" tf:"default_org_chart_view,omitempty"`

	// (Boolean) Indicates whether spend plans or budgets must be created on all projects.
	// Indicates whether spend plans or budgets must be created on all projects.
	EnforceFunding *bool `json:"enforceFunding,omitempty" tf:"enforce_funding,omitempty"`

	// (Boolean) Indicates whether every project should have a funding source.
	// Indicates whether every project should have a funding source.
	EnforceFundingSources *bool `json:"enforceFundingSources,omitempty" tf:"enforce_funding_sources,omitempty"`

	// (Boolean) Indicates whether event driven is enabled or not.
	// Indicates whether event driven is enabled or not.
	EventDrivenEnabled *bool `json:"eventDrivenEnabled,omitempty" tf:"event_driven_enabled,omitempty"`

	// (Boolean) Indicates whether forecasting is enabled or not.
	// Indicates whether forecasting is enabled or not.
	ForecastingEnabled *bool `json:"forecastingEnabled,omitempty" tf:"forecasting_enabled,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Indicates whether, when new groups are created via IDMS, the group will be set as a viewer by default.
	// Indicates whether, when new groups are created via IDMS, the group will be set as a viewer by default.
	IdmsGroupsAsViewersDefault *bool `json:"idmsGroupsAsViewersDefault,omitempty" tf:"idms_groups_as_viewers_default,omitempty"`

	// (Boolean) Indicates whether reserved instances are enabled or not.
	// Indicates whether reserved instances are enabled or not.
	ReservedInstancesEnabled *bool `json:"reservedInstancesEnabled,omitempty" tf:"reserved_instances_enabled,omitempty"`

	// (Boolean) Indicates whether resource inventory is enabled or not.
	// Indicates whether resource inventory is enabled or not.
	ResourceInventoryEnabled *bool `json:"resourceInventoryEnabled,omitempty" tf:"resource_inventory_enabled,omitempty"`

	// (Boolean) Indicates whether SAML debugging is enabled or not.
	// Indicates whether SAML debugging is enabled or not.
	SAMLDebug *bool `json:"samlDebug,omitempty" tf:"saml_debug,omitempty"`

	// (Boolean) Indicates whether SMTP is enabled or not.
	// Indicates whether SMTP is enabled or not.
	SMTPEnabled *bool `json:"smtpEnabled,omitempty" tf:"smtp_enabled,omitempty"`

	// (String) The SMTP from address.
	// The SMTP from address.
	SMTPFrom *string `json:"smtpFrom,omitempty" tf:"smtp_from,omitempty"`

	// (String) The SMTP host.
	// The SMTP host.
	SMTPHost *string `json:"smtpHost,omitempty" tf:"smtp_host,omitempty"`

	// (Number) The SMTP port.
	// The SMTP port.
	SMTPPort *float64 `json:"smtpPort,omitempty" tf:"smtp_port,omitempty"`

	// (Boolean) Indicates if the app should skip SMTP verification.
	// Indicates if the app should skip SMTP verification.
	SMTPSkipVerify *bool `json:"smtpSkipVerify,omitempty" tf:"smtp_skip_verify,omitempty"`

	// (String) The SMTP username.
	// The SMTP username.
	SMTPUsername *string `json:"smtpUsername,omitempty" tf:"smtp_username,omitempty"`

	// (List of String) The list of supported AWS regions.
	// The list of supported AWS regions.
	SupportedAwsRegions []*string `json:"supportedAwsRegions,omitempty" tf:"supported_aws_regions,omitempty"`
}

type AppConfigParameters struct {

	// (Boolean) Indicates whether all users can see the names of OU's in the organization chart.
	// Indicates whether all users can see the names of OU's in the organization chart.
	// +kubebuilder:validation:Optional
	AllUsersSeeOuNames *bool `json:"allUsersSeeOuNames,omitempty" tf:"all_users_see_ou_names,omitempty"`

	// (Boolean) Indicates if allocation mode is enabled in the application.
	// Indicates if allocation mode is enabled in the application.
	// +kubebuilder:validation:Optional
	AllocationMode *bool `json:"allocationMode,omitempty" tf:"allocation_mode,omitempty"`

	// (Boolean) Indicates whether custom permission schemes are allowed or not.
	// Indicates whether custom permission schemes are allowed or not.
	// +kubebuilder:validation:Optional
	AllowCustomPermissionSchemes *bool `json:"allowCustomPermissionSchemes,omitempty" tf:"allow_custom_permission_schemes,omitempty"`

	// (Boolean) Indicates if App API Key creation is enabled.
	// Indicates if App API Key creation is enabled.
	// +kubebuilder:validation:Optional
	AppAPIKeyCreationEnabled *bool `json:"appApiKeyCreationEnabled,omitempty" tf:"app_api_key_creation_enabled,omitempty"`

	// (Number) Indicates the lifespan of App API Keys in days.
	// Indicates the lifespan of App API Keys in days.
	// +kubebuilder:validation:Optional
	AppAPIKeyLifespan *float64 `json:"appApiKeyLifespan,omitempty" tf:"app_api_key_lifespan,omitempty"`

	// (Number) Indicates the max amount of App API Keys per user.
	// Indicates the max amount of App API Keys per user.
	// +kubebuilder:validation:Optional
	AppAPIKeyLimit *float64 `json:"appApiKeyLimit,omitempty" tf:"app_api_key_limit,omitempty"`

	// (Boolean) Indicates whether AWS access keys creation is enabled.
	// Indicates whether AWS access keys creation is enabled.
	// +kubebuilder:validation:Optional
	AwsAccessKeyCreationEnabled *bool `json:"awsAccessKeyCreationEnabled,omitempty" tf:"aws_access_key_creation_enabled,omitempty"`

	// (Boolean) Indicates if budget mode is enabled in the application.
	// Indicates if budget mode is enabled in the application.
	// +kubebuilder:validation:Optional
	BudgetMode *bool `json:"budgetMode,omitempty" tf:"budget_mode,omitempty"`

	// (Boolean) Indicates if cloud rules are restricted to User Group ownership only. Setting this to true will remove all users from cloud rules. This cannot be undone.
	// Indicates if cloud rules are restricted to User Group ownership only. Setting this to true will remove all users from cloud rules. This cannot be undone.
	// +kubebuilder:validation:Optional
	CloudRuleGroupOwnershipOnly *bool `json:"cloudRuleGroupOwnershipOnly,omitempty" tf:"cloud_rule_group_ownership_only,omitempty"`

	// app.
	// Indicates whether resource termination is allowed in-app.
	// +kubebuilder:validation:Optional
	CostSavingsAllowTerminate *bool `json:"costSavingsAllowTerminate,omitempty" tf:"cost_savings_allow_terminate,omitempty"`

	// (Boolean) Indicates whether Cost Savings is enabled or not.
	// Indicates whether Cost Savings is enabled or not.
	// +kubebuilder:validation:Optional
	CostSavingsEnabled *bool `json:"costSavingsEnabled,omitempty" tf:"cost_savings_enabled,omitempty"`

	// (Number) Post token life (hours) for Cloud Custodian webhook actions to execute.
	// Post token life (hours) for Cloud Custodian webhook actions to execute.
	// +kubebuilder:validation:Optional
	CostSavingsPostTokenLifeHours *float64 `json:"costSavingsPostTokenLifeHours,omitempty" tf:"cost_savings_post_token_life_hours,omitempty"`

	// (String) Defines the default organization chart view.
	// Defines the default organization chart view.
	// +kubebuilder:validation:Optional
	DefaultOrgChartView *string `json:"defaultOrgChartView,omitempty" tf:"default_org_chart_view,omitempty"`

	// (Boolean) Indicates whether spend plans or budgets must be created on all projects.
	// Indicates whether spend plans or budgets must be created on all projects.
	// +kubebuilder:validation:Optional
	EnforceFunding *bool `json:"enforceFunding,omitempty" tf:"enforce_funding,omitempty"`

	// (Boolean) Indicates whether every project should have a funding source.
	// Indicates whether every project should have a funding source.
	// +kubebuilder:validation:Optional
	EnforceFundingSources *bool `json:"enforceFundingSources,omitempty" tf:"enforce_funding_sources,omitempty"`

	// (Boolean) Indicates whether event driven is enabled or not.
	// Indicates whether event driven is enabled or not.
	// +kubebuilder:validation:Optional
	EventDrivenEnabled *bool `json:"eventDrivenEnabled,omitempty" tf:"event_driven_enabled,omitempty"`

	// (Boolean) Indicates whether forecasting is enabled or not.
	// Indicates whether forecasting is enabled or not.
	// +kubebuilder:validation:Optional
	ForecastingEnabled *bool `json:"forecastingEnabled,omitempty" tf:"forecasting_enabled,omitempty"`

	// (Boolean) Indicates whether, when new groups are created via IDMS, the group will be set as a viewer by default.
	// Indicates whether, when new groups are created via IDMS, the group will be set as a viewer by default.
	// +kubebuilder:validation:Optional
	IdmsGroupsAsViewersDefault *bool `json:"idmsGroupsAsViewersDefault,omitempty" tf:"idms_groups_as_viewers_default,omitempty"`

	// (Boolean) Indicates whether reserved instances are enabled or not.
	// Indicates whether reserved instances are enabled or not.
	// +kubebuilder:validation:Optional
	ReservedInstancesEnabled *bool `json:"reservedInstancesEnabled,omitempty" tf:"reserved_instances_enabled,omitempty"`

	// (Boolean) Indicates whether resource inventory is enabled or not.
	// Indicates whether resource inventory is enabled or not.
	// +kubebuilder:validation:Optional
	ResourceInventoryEnabled *bool `json:"resourceInventoryEnabled,omitempty" tf:"resource_inventory_enabled,omitempty"`

	// (Boolean) Indicates whether SAML debugging is enabled or not.
	// Indicates whether SAML debugging is enabled or not.
	// +kubebuilder:validation:Optional
	SAMLDebug *bool `json:"samlDebug,omitempty" tf:"saml_debug,omitempty"`

	// (Boolean) Indicates whether SMTP is enabled or not.
	// Indicates whether SMTP is enabled or not.
	// +kubebuilder:validation:Optional
	SMTPEnabled *bool `json:"smtpEnabled,omitempty" tf:"smtp_enabled,omitempty"`

	// (String) The SMTP from address.
	// The SMTP from address.
	// +kubebuilder:validation:Optional
	SMTPFrom *string `json:"smtpFrom,omitempty" tf:"smtp_from,omitempty"`

	// (String) The SMTP host.
	// The SMTP host.
	// +kubebuilder:validation:Optional
	SMTPHost *string `json:"smtpHost,omitempty" tf:"smtp_host,omitempty"`

	// (String, Sensitive) The SMTP password.
	// The SMTP password.
	// +kubebuilder:validation:Optional
	SMTPPasswordSecretRef *v1.LocalSecretKeySelector `json:"smtpPasswordSecretRef,omitempty" tf:"-"`

	// (Number) The SMTP port.
	// The SMTP port.
	// +kubebuilder:validation:Optional
	SMTPPort *float64 `json:"smtpPort,omitempty" tf:"smtp_port,omitempty"`

	// (Boolean) Indicates if the app should skip SMTP verification.
	// Indicates if the app should skip SMTP verification.
	// +kubebuilder:validation:Optional
	SMTPSkipVerify *bool `json:"smtpSkipVerify,omitempty" tf:"smtp_skip_verify,omitempty"`

	// (String) The SMTP username.
	// The SMTP username.
	// +kubebuilder:validation:Optional
	SMTPUsername *string `json:"smtpUsername,omitempty" tf:"smtp_username,omitempty"`

	// (List of String) The list of supported AWS regions.
	// The list of supported AWS regions.
	// +kubebuilder:validation:Optional
	SupportedAwsRegions []*string `json:"supportedAwsRegions,omitempty" tf:"supported_aws_regions,omitempty"`
}

// AppConfigSpec defines the desired state of AppConfig
type AppConfigSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AppConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AppConfigInitParameters `json:"initProvider,omitempty"`
}

// AppConfigStatus defines the observed state of AppConfig.
type AppConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AppConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AppConfig is the Schema for the AppConfigs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,kion}
type AppConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AppConfigSpec   `json:"spec"`
	Status            AppConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AppConfigList contains a list of AppConfigs
type AppConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AppConfig `json:"items"`
}

// Repository type metadata.
var (
	AppConfig_Kind             = "AppConfig"
	AppConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AppConfig_Kind}.String()
	AppConfig_KindAPIVersion   = AppConfig_Kind + "." + CRDGroupVersion.String()
	AppConfig_GroupVersionKind = CRDGroupVersion.WithKind(AppConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&AppConfig{}, &AppConfigList{})
}
