//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetInitParameters) DeepCopyInto(out *BudgetInitParameters) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]DataInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EndDatecode != nil {
		in, out := &in.EndDatecode, &out.EndDatecode
		*out = new(string)
		**out = **in
	}
	if in.FundingSourceIds != nil {
		in, out := &in.FundingSourceIds, &out.FundingSourceIds
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.StartDatecode != nil {
		in, out := &in.StartDatecode, &out.StartDatecode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetInitParameters.
func (in *BudgetInitParameters) DeepCopy() *BudgetInitParameters {
	if in == nil {
		return nil
	}
	out := new(BudgetInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetObservation) DeepCopyInto(out *BudgetObservation) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]DataObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EndDatecode != nil {
		in, out := &in.EndDatecode, &out.EndDatecode
		*out = new(string)
		**out = **in
	}
	if in.FundingSourceIds != nil {
		in, out := &in.FundingSourceIds, &out.FundingSourceIds
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.StartDatecode != nil {
		in, out := &in.StartDatecode, &out.StartDatecode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetObservation.
func (in *BudgetObservation) DeepCopy() *BudgetObservation {
	if in == nil {
		return nil
	}
	out := new(BudgetObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetParameters) DeepCopyInto(out *BudgetParameters) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]DataParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EndDatecode != nil {
		in, out := &in.EndDatecode, &out.EndDatecode
		*out = new(string)
		**out = **in
	}
	if in.FundingSourceIds != nil {
		in, out := &in.FundingSourceIds, &out.FundingSourceIds
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.StartDatecode != nil {
		in, out := &in.StartDatecode, &out.StartDatecode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetParameters.
func (in *BudgetParameters) DeepCopy() *BudgetParameters {
	if in == nil {
		return nil
	}
	out := new(BudgetParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataInitParameters) DeepCopyInto(out *DataInitParameters) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.Datecode != nil {
		in, out := &in.Datecode, &out.Datecode
		*out = new(string)
		**out = **in
	}
	if in.FundingSourceID != nil {
		in, out := &in.FundingSourceID, &out.FundingSourceID
		*out = new(float64)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataInitParameters.
func (in *DataInitParameters) DeepCopy() *DataInitParameters {
	if in == nil {
		return nil
	}
	out := new(DataInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataObservation) DeepCopyInto(out *DataObservation) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.Datecode != nil {
		in, out := &in.Datecode, &out.Datecode
		*out = new(string)
		**out = **in
	}
	if in.FundingSourceID != nil {
		in, out := &in.FundingSourceID, &out.FundingSourceID
		*out = new(float64)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataObservation.
func (in *DataObservation) DeepCopy() *DataObservation {
	if in == nil {
		return nil
	}
	out := new(DataObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataParameters) DeepCopyInto(out *DataParameters) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.Datecode != nil {
		in, out := &in.Datecode, &out.Datecode
		*out = new(string)
		**out = **in
	}
	if in.FundingSourceID != nil {
		in, out := &in.FundingSourceID, &out.FundingSourceID
		*out = new(float64)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataParameters.
func (in *DataParameters) DeepCopy() *DataParameters {
	if in == nil {
		return nil
	}
	out := new(DataParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnerUserGroupIdsInitParameters) DeepCopyInto(out *OwnerUserGroupIdsInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnerUserGroupIdsInitParameters.
func (in *OwnerUserGroupIdsInitParameters) DeepCopy() *OwnerUserGroupIdsInitParameters {
	if in == nil {
		return nil
	}
	out := new(OwnerUserGroupIdsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnerUserGroupIdsObservation) DeepCopyInto(out *OwnerUserGroupIdsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnerUserGroupIdsObservation.
func (in *OwnerUserGroupIdsObservation) DeepCopy() *OwnerUserGroupIdsObservation {
	if in == nil {
		return nil
	}
	out := new(OwnerUserGroupIdsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnerUserGroupIdsParameters) DeepCopyInto(out *OwnerUserGroupIdsParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnerUserGroupIdsParameters.
func (in *OwnerUserGroupIdsParameters) DeepCopy() *OwnerUserGroupIdsParameters {
	if in == nil {
		return nil
	}
	out := new(OwnerUserGroupIdsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnerUserIdsInitParameters) DeepCopyInto(out *OwnerUserIdsInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnerUserIdsInitParameters.
func (in *OwnerUserIdsInitParameters) DeepCopy() *OwnerUserIdsInitParameters {
	if in == nil {
		return nil
	}
	out := new(OwnerUserIdsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnerUserIdsObservation) DeepCopyInto(out *OwnerUserIdsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnerUserIdsObservation.
func (in *OwnerUserIdsObservation) DeepCopy() *OwnerUserIdsObservation {
	if in == nil {
		return nil
	}
	out := new(OwnerUserIdsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnerUserIdsParameters) DeepCopyInto(out *OwnerUserIdsParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnerUserIdsParameters.
func (in *OwnerUserIdsParameters) DeepCopy() *OwnerUserIdsParameters {
	if in == nil {
		return nil
	}
	out := new(OwnerUserIdsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Project.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectFundingInitParameters) DeepCopyInto(out *ProjectFundingInitParameters) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.EndDatecode != nil {
		in, out := &in.EndDatecode, &out.EndDatecode
		*out = new(string)
		**out = **in
	}
	if in.FundingOrder != nil {
		in, out := &in.FundingOrder, &out.FundingOrder
		*out = new(float64)
		**out = **in
	}
	if in.FundingSourceID != nil {
		in, out := &in.FundingSourceID, &out.FundingSourceID
		*out = new(float64)
		**out = **in
	}
	if in.StartDatecode != nil {
		in, out := &in.StartDatecode, &out.StartDatecode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectFundingInitParameters.
func (in *ProjectFundingInitParameters) DeepCopy() *ProjectFundingInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectFundingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectFundingObservation) DeepCopyInto(out *ProjectFundingObservation) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.EndDatecode != nil {
		in, out := &in.EndDatecode, &out.EndDatecode
		*out = new(string)
		**out = **in
	}
	if in.FundingOrder != nil {
		in, out := &in.FundingOrder, &out.FundingOrder
		*out = new(float64)
		**out = **in
	}
	if in.FundingSourceID != nil {
		in, out := &in.FundingSourceID, &out.FundingSourceID
		*out = new(float64)
		**out = **in
	}
	if in.StartDatecode != nil {
		in, out := &in.StartDatecode, &out.StartDatecode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectFundingObservation.
func (in *ProjectFundingObservation) DeepCopy() *ProjectFundingObservation {
	if in == nil {
		return nil
	}
	out := new(ProjectFundingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectFundingParameters) DeepCopyInto(out *ProjectFundingParameters) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.EndDatecode != nil {
		in, out := &in.EndDatecode, &out.EndDatecode
		*out = new(string)
		**out = **in
	}
	if in.FundingOrder != nil {
		in, out := &in.FundingOrder, &out.FundingOrder
		*out = new(float64)
		**out = **in
	}
	if in.FundingSourceID != nil {
		in, out := &in.FundingSourceID, &out.FundingSourceID
		*out = new(float64)
		**out = **in
	}
	if in.StartDatecode != nil {
		in, out := &in.StartDatecode, &out.StartDatecode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectFundingParameters.
func (in *ProjectFundingParameters) DeepCopy() *ProjectFundingParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectFundingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInitParameters) DeepCopyInto(out *ProjectInitParameters) {
	*out = *in
	if in.AutoPay != nil {
		in, out := &in.AutoPay, &out.AutoPay
		*out = new(bool)
		**out = **in
	}
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = make([]BudgetInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultAwsRegion != nil {
		in, out := &in.DefaultAwsRegion, &out.DefaultAwsRegion
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OuID != nil {
		in, out := &in.OuID, &out.OuID
		*out = new(float64)
		**out = **in
	}
	if in.OwnerUserGroupIds != nil {
		in, out := &in.OwnerUserGroupIds, &out.OwnerUserGroupIds
		*out = make([]OwnerUserGroupIdsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OwnerUserIds != nil {
		in, out := &in.OwnerUserIds, &out.OwnerUserIds
		*out = make([]OwnerUserIdsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PermissionSchemeID != nil {
		in, out := &in.PermissionSchemeID, &out.PermissionSchemeID
		*out = new(float64)
		**out = **in
	}
	if in.ProjectFunding != nil {
		in, out := &in.ProjectFunding, &out.ProjectFunding
		*out = make([]ProjectFundingInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInitParameters.
func (in *ProjectInitParameters) DeepCopy() *ProjectInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Project, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectList.
func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectObservation) DeepCopyInto(out *ProjectObservation) {
	*out = *in
	if in.Archived != nil {
		in, out := &in.Archived, &out.Archived
		*out = new(bool)
		**out = **in
	}
	if in.AutoPay != nil {
		in, out := &in.AutoPay, &out.AutoPay
		*out = new(bool)
		**out = **in
	}
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = make([]BudgetObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultAwsRegion != nil {
		in, out := &in.DefaultAwsRegion, &out.DefaultAwsRegion
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OuID != nil {
		in, out := &in.OuID, &out.OuID
		*out = new(float64)
		**out = **in
	}
	if in.OwnerUserGroupIds != nil {
		in, out := &in.OwnerUserGroupIds, &out.OwnerUserGroupIds
		*out = make([]OwnerUserGroupIdsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OwnerUserIds != nil {
		in, out := &in.OwnerUserIds, &out.OwnerUserIds
		*out = make([]OwnerUserIdsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PermissionSchemeID != nil {
		in, out := &in.PermissionSchemeID, &out.PermissionSchemeID
		*out = new(float64)
		**out = **in
	}
	if in.ProjectFunding != nil {
		in, out := &in.ProjectFunding, &out.ProjectFunding
		*out = make([]ProjectFundingObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectObservation.
func (in *ProjectObservation) DeepCopy() *ProjectObservation {
	if in == nil {
		return nil
	}
	out := new(ProjectObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectParameters) DeepCopyInto(out *ProjectParameters) {
	*out = *in
	if in.AutoPay != nil {
		in, out := &in.AutoPay, &out.AutoPay
		*out = new(bool)
		**out = **in
	}
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = make([]BudgetParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultAwsRegion != nil {
		in, out := &in.DefaultAwsRegion, &out.DefaultAwsRegion
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OuID != nil {
		in, out := &in.OuID, &out.OuID
		*out = new(float64)
		**out = **in
	}
	if in.OwnerUserGroupIds != nil {
		in, out := &in.OwnerUserGroupIds, &out.OwnerUserGroupIds
		*out = make([]OwnerUserGroupIdsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OwnerUserIds != nil {
		in, out := &in.OwnerUserIds, &out.OwnerUserIds
		*out = make([]OwnerUserIdsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PermissionSchemeID != nil {
		in, out := &in.PermissionSchemeID, &out.PermissionSchemeID
		*out = new(float64)
		**out = **in
	}
	if in.ProjectFunding != nil {
		in, out := &in.ProjectFunding, &out.ProjectFunding
		*out = make([]ProjectFundingParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectParameters.
func (in *ProjectParameters) DeepCopy() *ProjectParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSpec.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectStatus.
func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}
