// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CustomVariableInitParameters struct {

	// (List of String)
	DefaultValueList []*string `json:"defaultValueList,omitempty" tf:"default_value_list,omitempty"`

	// (Map of String)
	// +mapType=granular
	DefaultValueMap map[string]*string `json:"defaultValueMap,omitempty" tf:"default_value_map,omitempty"`

	// (String)
	DefaultValueString *string `json:"defaultValueString,omitempty" tf:"default_value_string,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	KeyValidationMessage *string `json:"keyValidationMessage,omitempty" tf:"key_validation_message,omitempty"`

	// (String)
	KeyValidationRegex *string `json:"keyValidationRegex,omitempty" tf:"key_validation_regex,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of Number)
	// +listType=set
	OwnerUserGroupIds []*float64 `json:"ownerUserGroupIds,omitempty" tf:"owner_user_group_ids,omitempty"`

	// (Set of Number)
	// +listType=set
	OwnerUserIds []*float64 `json:"ownerUserIds,omitempty" tf:"owner_user_ids,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	ValueValidationMessage *string `json:"valueValidationMessage,omitempty" tf:"value_validation_message,omitempty"`

	// (String)
	ValueValidationRegex *string `json:"valueValidationRegex,omitempty" tf:"value_validation_regex,omitempty"`
}

type CustomVariableObservation struct {

	// (List of String)
	DefaultValueList []*string `json:"defaultValueList,omitempty" tf:"default_value_list,omitempty"`

	// (Map of String)
	// +mapType=granular
	DefaultValueMap map[string]*string `json:"defaultValueMap,omitempty" tf:"default_value_map,omitempty"`

	// (String)
	DefaultValueString *string `json:"defaultValueString,omitempty" tf:"default_value_string,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	KeyValidationMessage *string `json:"keyValidationMessage,omitempty" tf:"key_validation_message,omitempty"`

	// (String)
	KeyValidationRegex *string `json:"keyValidationRegex,omitempty" tf:"key_validation_regex,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of Number)
	// +listType=set
	OwnerUserGroupIds []*float64 `json:"ownerUserGroupIds,omitempty" tf:"owner_user_group_ids,omitempty"`

	// (Set of Number)
	// +listType=set
	OwnerUserIds []*float64 `json:"ownerUserIds,omitempty" tf:"owner_user_ids,omitempty"`

	// (String)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	ValueValidationMessage *string `json:"valueValidationMessage,omitempty" tf:"value_validation_message,omitempty"`

	// (String)
	ValueValidationRegex *string `json:"valueValidationRegex,omitempty" tf:"value_validation_regex,omitempty"`
}

type CustomVariableParameters struct {

	// (List of String)
	// +kubebuilder:validation:Optional
	DefaultValueList []*string `json:"defaultValueList,omitempty" tf:"default_value_list,omitempty"`

	// (Map of String)
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefaultValueMap map[string]*string `json:"defaultValueMap,omitempty" tf:"default_value_map,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	DefaultValueString *string `json:"defaultValueString,omitempty" tf:"default_value_string,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	KeyValidationMessage *string `json:"keyValidationMessage,omitempty" tf:"key_validation_message,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	KeyValidationRegex *string `json:"keyValidationRegex,omitempty" tf:"key_validation_regex,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of Number)
	// +kubebuilder:validation:Optional
	// +listType=set
	OwnerUserGroupIds []*float64 `json:"ownerUserGroupIds,omitempty" tf:"owner_user_group_ids,omitempty"`

	// (Set of Number)
	// +kubebuilder:validation:Optional
	// +listType=set
	OwnerUserIds []*float64 `json:"ownerUserIds,omitempty" tf:"owner_user_ids,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	ValueValidationMessage *string `json:"valueValidationMessage,omitempty" tf:"value_validation_message,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	ValueValidationRegex *string `json:"valueValidationRegex,omitempty" tf:"value_validation_regex,omitempty"`
}

// CustomVariableSpec defines the desired state of CustomVariable
type CustomVariableSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CustomVariableParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CustomVariableInitParameters `json:"initProvider,omitempty"`
}

// CustomVariableStatus defines the observed state of CustomVariable.
type CustomVariableStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CustomVariableObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CustomVariable is the Schema for the CustomVariables API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type CustomVariable struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.keyValidationMessage) || (has(self.initProvider) && has(self.initProvider.keyValidationMessage))",message="spec.forProvider.keyValidationMessage is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.keyValidationRegex) || (has(self.initProvider) && has(self.initProvider.keyValidationRegex))",message="spec.forProvider.keyValidationRegex is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.valueValidationMessage) || (has(self.initProvider) && has(self.initProvider.valueValidationMessage))",message="spec.forProvider.valueValidationMessage is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.valueValidationRegex) || (has(self.initProvider) && has(self.initProvider.valueValidationRegex))",message="spec.forProvider.valueValidationRegex is a required parameter"
	Spec   CustomVariableSpec   `json:"spec"`
	Status CustomVariableStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomVariableList contains a list of CustomVariables
type CustomVariableList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomVariable `json:"items"`
}

// Repository type metadata.
var (
	CustomVariable_Kind             = "CustomVariable"
	CustomVariable_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CustomVariable_Kind}.String()
	CustomVariable_KindAPIVersion   = CustomVariable_Kind + "." + CRDGroupVersion.String()
	CustomVariable_GroupVersionKind = CRDGroupVersion.WithKind(CustomVariable_Kind)
)

func init() {
	SchemeBuilder.Register(&CustomVariable{}, &CustomVariableList{})
}
