// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CustomAccountInitParameters struct {

	// (String) Account alias is an optional short unique name that helps identify the account within Kion.
	// Account alias is an optional short unique name that helps identify the account within Kion.
	AccountAlias *string `json:"accountAlias,omitempty" tf:"account_alias,omitempty"`

	// (String) The account number of the custom account.
	// The account number of the custom account.
	AccountNumber *string `json:"accountNumber,omitempty" tf:"account_number,omitempty"`

	// (Number) An ID representing the account type within Kion.
	// An ID representing the account type within Kion.
	AccountTypeID *float64 `json:"accountTypeId,omitempty" tf:"account_type_id,omitempty"`

	// (Map of String) A map of labels to assign to the account. The labels must already exist in Kion.
	// A map of labels to assign to the account. The labels must already exist in Kion.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String) The name of the custom account within Kion.
	// The name of the custom account within Kion.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The ID of the billing source containing billing data for this account.
	// The ID of the billing source containing billing data for this account.
	PayerID *float64 `json:"payerId,omitempty" tf:"payer_id,omitempty"`

	// (Number) The ID of the Kion project to place this account within. If empty, the account will be placed within the account cache.
	// The ID of the Kion project to place this account within. If empty, the account will be placed within the account cache.
	// +crossplane:generate:reference:type=github.com/enel1221/provider-kion/apis/cluster/kion/v1alpha1.Project
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in kion to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in kion to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Boolean) True to skip periodic access checking on the account.
	// True to skip periodic access checking on the account.
	SkipAccessChecking *bool `json:"skipAccessChecking,omitempty" tf:"skip_access_checking,omitempty"`

	// MM). Required if placing an account within a project.
	// Date when the custom account will starting submitting payments against a funding source (YYYY-MM). Required if placing an account within a project.
	StartDatecode *string `json:"startDatecode,omitempty" tf:"start_datecode,omitempty"`
}

type CustomAccountObservation struct {

	// (String) Account alias is an optional short unique name that helps identify the account within Kion.
	// Account alias is an optional short unique name that helps identify the account within Kion.
	AccountAlias *string `json:"accountAlias,omitempty" tf:"account_alias,omitempty"`

	// (String) The account number of the custom account.
	// The account number of the custom account.
	AccountNumber *string `json:"accountNumber,omitempty" tf:"account_number,omitempty"`

	// (Number) An ID representing the account type within Kion.
	// An ID representing the account type within Kion.
	AccountTypeID *float64 `json:"accountTypeId,omitempty" tf:"account_type_id,omitempty"`

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of String) A map of labels to assign to the account. The labels must already exist in Kion.
	// A map of labels to assign to the account. The labels must already exist in Kion.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String) Where the account is attached. Either "project" or "cache".
	// Where the account is attached. Either "project" or "cache".
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// (String) The name of the custom account within Kion.
	// The name of the custom account within Kion.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The ID of the billing source containing billing data for this account.
	// The ID of the billing source containing billing data for this account.
	PayerID *float64 `json:"payerId,omitempty" tf:"payer_id,omitempty"`

	// (Number) The ID of the Kion project to place this account within. If empty, the account will be placed within the account cache.
	// The ID of the Kion project to place this account within. If empty, the account will be placed within the account cache.
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Boolean) True to skip periodic access checking on the account.
	// True to skip periodic access checking on the account.
	SkipAccessChecking *bool `json:"skipAccessChecking,omitempty" tf:"skip_access_checking,omitempty"`

	// MM). Required if placing an account within a project.
	// Date when the custom account will starting submitting payments against a funding source (YYYY-MM). Required if placing an account within a project.
	StartDatecode *string `json:"startDatecode,omitempty" tf:"start_datecode,omitempty"`
}

type CustomAccountParameters struct {

	// (String) Account alias is an optional short unique name that helps identify the account within Kion.
	// Account alias is an optional short unique name that helps identify the account within Kion.
	// +kubebuilder:validation:Optional
	AccountAlias *string `json:"accountAlias,omitempty" tf:"account_alias,omitempty"`

	// (String) The account number of the custom account.
	// The account number of the custom account.
	// +kubebuilder:validation:Optional
	AccountNumber *string `json:"accountNumber,omitempty" tf:"account_number,omitempty"`

	// (Number) An ID representing the account type within Kion.
	// An ID representing the account type within Kion.
	// +kubebuilder:validation:Optional
	AccountTypeID *float64 `json:"accountTypeId,omitempty" tf:"account_type_id,omitempty"`

	// (Map of String) A map of labels to assign to the account. The labels must already exist in Kion.
	// A map of labels to assign to the account. The labels must already exist in Kion.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String) The name of the custom account within Kion.
	// The name of the custom account within Kion.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The ID of the billing source containing billing data for this account.
	// The ID of the billing source containing billing data for this account.
	// +kubebuilder:validation:Optional
	PayerID *float64 `json:"payerId,omitempty" tf:"payer_id,omitempty"`

	// (Number) The ID of the Kion project to place this account within. If empty, the account will be placed within the account cache.
	// The ID of the Kion project to place this account within. If empty, the account will be placed within the account cache.
	// +crossplane:generate:reference:type=github.com/enel1221/provider-kion/apis/cluster/kion/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *float64 `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in kion to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in kion to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Boolean) True to skip periodic access checking on the account.
	// True to skip periodic access checking on the account.
	// +kubebuilder:validation:Optional
	SkipAccessChecking *bool `json:"skipAccessChecking,omitempty" tf:"skip_access_checking,omitempty"`

	// MM). Required if placing an account within a project.
	// Date when the custom account will starting submitting payments against a funding source (YYYY-MM). Required if placing an account within a project.
	// +kubebuilder:validation:Optional
	StartDatecode *string `json:"startDatecode,omitempty" tf:"start_datecode,omitempty"`
}

// CustomAccountSpec defines the desired state of CustomAccount
type CustomAccountSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CustomAccountParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CustomAccountInitParameters `json:"initProvider,omitempty"`
}

// CustomAccountStatus defines the observed state of CustomAccount.
type CustomAccountStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CustomAccountObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CustomAccount is the Schema for the CustomAccounts API. Attaches a custom account to a project in Kion. If project_id is provided, the account will be added to the corresponding project, otherwise the account will be added to the account cache. Once added, an account can be moved between projects or in and out of the account cache by changing the project_id
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,kion}
type CustomAccount struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountNumber) || (has(self.initProvider) && has(self.initProvider.accountNumber))",message="spec.forProvider.accountNumber is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.payerId) || (has(self.initProvider) && has(self.initProvider.payerId))",message="spec.forProvider.payerId is a required parameter"
	Spec   CustomAccountSpec   `json:"spec"`
	Status CustomAccountStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomAccountList contains a list of CustomAccounts
type CustomAccountList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomAccount `json:"items"`
}

// Repository type metadata.
var (
	CustomAccount_Kind             = "CustomAccount"
	CustomAccount_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CustomAccount_Kind}.String()
	CustomAccount_KindAPIVersion   = CustomAccount_Kind + "." + CRDGroupVersion.String()
	CustomAccount_GroupVersionKind = CRDGroupVersion.WithKind(CustomAccount_Kind)
)

func init() {
	SchemeBuilder.Register(&CustomAccount{}, &CustomAccountList{})
}
