apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kion
spec:
  crossplane:
    version: ">=v2.0.0"
  capabilities:
    # Required by Crossplane Runtime's customresourcesgate safe-start controller.
    - safe-start
